# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pyproto/com.bapis.bilibili.app.show.popular.v1.PopularReply.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pyproto.com.bapis.bilibili.app.card.v1 import Card_pb2 as pyproto_dot_com_dot_bapis_dot_bilibili_dot_app_dot_card_dot_v1_dot_Card__pb2
from pyproto.com.bapis.bilibili.app.show.popular.v1 import Config_pb2 as pyproto_dot_com_dot_bapis_dot_bilibili_dot_app_dot_show_dot_popular_dot_v1_dot_Config__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pyproto/com.bapis.bilibili.app.show.popular.v1.PopularReply.proto',
  package='com.bapis.bilibili.app.show.popular.v1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nApyproto/com.bapis.bilibili.app.show.popular.v1.PopularReply.proto\x12&com.bapis.bilibili.app.show.popular.v1\x1a\x31pyproto/com.bapis.bilibili.app.card.v1.Card.proto\x1a;pyproto/com.bapis.bilibili.app.show.popular.v1.Config.proto\"\xad\x01\n\x0cPopularReply\x12\x33\n\x05items\x18\x01 \x03(\x0b\x32$.com.bapis.bilibili.app.card.v1.Card\x12\x43\n\x06\x63onfig\x18\x02 \x01(\x0b\x32..com.bapis.bilibili.app.show.popular.v1.ConfigH\x00\x88\x01\x01\x12\x10\n\x03ver\x18\x03 \x01(\tH\x01\x88\x01\x01\x42\t\n\x07_configB\x06\n\x04_verb\x06proto3'
  ,
  dependencies=[pyproto_dot_com_dot_bapis_dot_bilibili_dot_app_dot_card_dot_v1_dot_Card__pb2.DESCRIPTOR,pyproto_dot_com_dot_bapis_dot_bilibili_dot_app_dot_show_dot_popular_dot_v1_dot_Config__pb2.DESCRIPTOR,])




_POPULARREPLY = _descriptor.Descriptor(
  name='PopularReply',
  full_name='com.bapis.bilibili.app.show.popular.v1.PopularReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='com.bapis.bilibili.app.show.popular.v1.PopularReply.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='config', full_name='com.bapis.bilibili.app.show.popular.v1.PopularReply.config', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ver', full_name='com.bapis.bilibili.app.show.popular.v1.PopularReply.ver', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_config', full_name='com.bapis.bilibili.app.show.popular.v1.PopularReply._config',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_ver', full_name='com.bapis.bilibili.app.show.popular.v1.PopularReply._ver',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=222,
  serialized_end=395,
)

_POPULARREPLY.fields_by_name['items'].message_type = pyproto_dot_com_dot_bapis_dot_bilibili_dot_app_dot_card_dot_v1_dot_Card__pb2._CARD
_POPULARREPLY.fields_by_name['config'].message_type = pyproto_dot_com_dot_bapis_dot_bilibili_dot_app_dot_show_dot_popular_dot_v1_dot_Config__pb2._CONFIG
_POPULARREPLY.oneofs_by_name['_config'].fields.append(
  _POPULARREPLY.fields_by_name['config'])
_POPULARREPLY.fields_by_name['config'].containing_oneof = _POPULARREPLY.oneofs_by_name['_config']
_POPULARREPLY.oneofs_by_name['_ver'].fields.append(
  _POPULARREPLY.fields_by_name['ver'])
_POPULARREPLY.fields_by_name['ver'].containing_oneof = _POPULARREPLY.oneofs_by_name['_ver']
DESCRIPTOR.message_types_by_name['PopularReply'] = _POPULARREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PopularReply = _reflection.GeneratedProtocolMessageType('PopularReply', (_message.Message,), {
  'DESCRIPTOR' : _POPULARREPLY,
  '__module__' : 'pyproto.com.bapis.bilibili.app.show.popular.v1.PopularReply_pb2'
  # @@protoc_insertion_point(class_scope:com.bapis.bilibili.app.show.popular.v1.PopularReply)
  })
_sym_db.RegisterMessage(PopularReply)


# @@protoc_insertion_point(module_scope)
