# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pyproto/tbclient.GetBubbleList.GetBubbleListResIdl.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pyproto.tbclient import Error_pb2 as pyproto_dot_tbclient_dot_Error__pb2
from pyproto.tbclient.GetBubbleList import DataRes_pb2 as pyproto_dot_tbclient_dot_GetBubbleList_dot_DataRes__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pyproto/tbclient.GetBubbleList.GetBubbleListResIdl.proto',
  package='tbclient.GetBubbleList',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n8pyproto/tbclient.GetBubbleList.GetBubbleListResIdl.proto\x12\x16tbclient.GetBubbleList\x1a\x1cpyproto/tbclient.Error.proto\x1a,pyproto/tbclient.GetBubbleList.DataRes.proto\"\x81\x01\n\x13GetBubbleListResIdl\x12\x32\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x1f.tbclient.GetBubbleList.DataResH\x00\x88\x01\x01\x12#\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x0f.tbclient.ErrorH\x01\x88\x01\x01\x42\x07\n\x05_dataB\x08\n\x06_errorb\x06proto3'
  ,
  dependencies=[pyproto_dot_tbclient_dot_Error__pb2.DESCRIPTOR,pyproto_dot_tbclient_dot_GetBubbleList_dot_DataRes__pb2.DESCRIPTOR,])




_GETBUBBLELISTRESIDL = _descriptor.Descriptor(
  name='GetBubbleListResIdl',
  full_name='tbclient.GetBubbleList.GetBubbleListResIdl',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='tbclient.GetBubbleList.GetBubbleListResIdl.data', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error', full_name='tbclient.GetBubbleList.GetBubbleListResIdl.error', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_data', full_name='tbclient.GetBubbleList.GetBubbleListResIdl._data',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_error', full_name='tbclient.GetBubbleList.GetBubbleListResIdl._error',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=161,
  serialized_end=290,
)

_GETBUBBLELISTRESIDL.fields_by_name['data'].message_type = pyproto_dot_tbclient_dot_GetBubbleList_dot_DataRes__pb2._DATARES
_GETBUBBLELISTRESIDL.fields_by_name['error'].message_type = pyproto_dot_tbclient_dot_Error__pb2._ERROR
_GETBUBBLELISTRESIDL.oneofs_by_name['_data'].fields.append(
  _GETBUBBLELISTRESIDL.fields_by_name['data'])
_GETBUBBLELISTRESIDL.fields_by_name['data'].containing_oneof = _GETBUBBLELISTRESIDL.oneofs_by_name['_data']
_GETBUBBLELISTRESIDL.oneofs_by_name['_error'].fields.append(
  _GETBUBBLELISTRESIDL.fields_by_name['error'])
_GETBUBBLELISTRESIDL.fields_by_name['error'].containing_oneof = _GETBUBBLELISTRESIDL.oneofs_by_name['_error']
DESCRIPTOR.message_types_by_name['GetBubbleListResIdl'] = _GETBUBBLELISTRESIDL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetBubbleListResIdl = _reflection.GeneratedProtocolMessageType('GetBubbleListResIdl', (_message.Message,), {
  'DESCRIPTOR' : _GETBUBBLELISTRESIDL,
  '__module__' : 'pyproto.tbclient.GetBubbleList.GetBubbleListResIdl_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.GetBubbleList.GetBubbleListResIdl)
  })
_sym_db.RegisterMessage(GetBubbleListResIdl)


# @@protoc_insertion_point(module_scope)
