# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pyproto/CommonStyleMap.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pyproto/CommonStyleMap.proto',
  package='com.tencent.qqlive.protocol.pb',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1cpyproto/CommonStyleMap.proto\x12\x1e\x63om.tencent.qqlive.protocol.pb\"\x92\x01\n\x0e\x43ommonStyleMap\x12O\n\tstyle_map\x18\x01 \x03(\x0b\x32<.com.tencent.qqlive.protocol.pb.CommonStyleMap.StyleMapEntry\x1a/\n\rStyleMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3'
)




_COMMONSTYLEMAP_STYLEMAPENTRY = _descriptor.Descriptor(
  name='StyleMapEntry',
  full_name='com.tencent.qqlive.protocol.pb.CommonStyleMap.StyleMapEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='com.tencent.qqlive.protocol.pb.CommonStyleMap.StyleMapEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='com.tencent.qqlive.protocol.pb.CommonStyleMap.StyleMapEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=211,
)

_COMMONSTYLEMAP = _descriptor.Descriptor(
  name='CommonStyleMap',
  full_name='com.tencent.qqlive.protocol.pb.CommonStyleMap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='style_map', full_name='com.tencent.qqlive.protocol.pb.CommonStyleMap.style_map', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_COMMONSTYLEMAP_STYLEMAPENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=211,
)

_COMMONSTYLEMAP_STYLEMAPENTRY.containing_type = _COMMONSTYLEMAP
_COMMONSTYLEMAP.fields_by_name['style_map'].message_type = _COMMONSTYLEMAP_STYLEMAPENTRY
DESCRIPTOR.message_types_by_name['CommonStyleMap'] = _COMMONSTYLEMAP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CommonStyleMap = _reflection.GeneratedProtocolMessageType('CommonStyleMap', (_message.Message,), {

  'StyleMapEntry' : _reflection.GeneratedProtocolMessageType('StyleMapEntry', (_message.Message,), {
    'DESCRIPTOR' : _COMMONSTYLEMAP_STYLEMAPENTRY,
    '__module__' : 'pyproto.CommonStyleMap_pb2'
    # @@protoc_insertion_point(class_scope:com.tencent.qqlive.protocol.pb.CommonStyleMap.StyleMapEntry)
    })
  ,
  'DESCRIPTOR' : _COMMONSTYLEMAP,
  '__module__' : 'pyproto.CommonStyleMap_pb2'
  # @@protoc_insertion_point(class_scope:com.tencent.qqlive.protocol.pb.CommonStyleMap)
  })
_sym_db.RegisterMessage(CommonStyleMap)
_sym_db.RegisterMessage(CommonStyleMap.StyleMapEntry)


_COMMONSTYLEMAP_STYLEMAPENTRY._options = None
# @@protoc_insertion_point(module_scope)
