# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pyproto/ExtraData.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pyproto import Any_pb2 as pyproto_dot_Any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pyproto/ExtraData.proto',
  package='com.tencent.qqlive.protocol.pb',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17pyproto/ExtraData.proto\x12\x1e\x63om.tencent.qqlive.protocol.pb\x1a\x11pyproto/Any.proto\"\xa0\x01\n\tExtraData\x12\x41\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x33.com.tencent.qqlive.protocol.pb.ExtraData.DataEntry\x1aP\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x32\n\x05value\x18\x02 \x01(\x0b\x32#.com.tencent.qqlive.protocol.pb.Any:\x02\x38\x01\x62\x06proto3'
  ,
  dependencies=[pyproto_dot_Any__pb2.DESCRIPTOR,])




_EXTRADATA_DATAENTRY = _descriptor.Descriptor(
  name='DataEntry',
  full_name='com.tencent.qqlive.protocol.pb.ExtraData.DataEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='com.tencent.qqlive.protocol.pb.ExtraData.DataEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='com.tencent.qqlive.protocol.pb.ExtraData.DataEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=239,
)

_EXTRADATA = _descriptor.Descriptor(
  name='ExtraData',
  full_name='com.tencent.qqlive.protocol.pb.ExtraData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='com.tencent.qqlive.protocol.pb.ExtraData.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_EXTRADATA_DATAENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=239,
)

_EXTRADATA_DATAENTRY.fields_by_name['value'].message_type = pyproto_dot_Any__pb2._ANY
_EXTRADATA_DATAENTRY.containing_type = _EXTRADATA
_EXTRADATA.fields_by_name['data'].message_type = _EXTRADATA_DATAENTRY
DESCRIPTOR.message_types_by_name['ExtraData'] = _EXTRADATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ExtraData = _reflection.GeneratedProtocolMessageType('ExtraData', (_message.Message,), {

  'DataEntry' : _reflection.GeneratedProtocolMessageType('DataEntry', (_message.Message,), {
    'DESCRIPTOR' : _EXTRADATA_DATAENTRY,
    '__module__' : 'pyproto.ExtraData_pb2'
    # @@protoc_insertion_point(class_scope:com.tencent.qqlive.protocol.pb.ExtraData.DataEntry)
    })
  ,
  'DESCRIPTOR' : _EXTRADATA,
  '__module__' : 'pyproto.ExtraData_pb2'
  # @@protoc_insertion_point(class_scope:com.tencent.qqlive.protocol.pb.ExtraData)
  })
_sym_db.RegisterMessage(ExtraData)
_sym_db.RegisterMessage(ExtraData.DataEntry)


_EXTRADATA_DATAENTRY._options = None
# @@protoc_insertion_point(module_scope)
