# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pyproto/MarkLabelType.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pyproto/MarkLabelType.proto',
  package='com.tencent.qqlive.protocol.pb',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1bpyproto/MarkLabelType.proto\x12\x1e\x63om.tencent.qqlive.protocol.pb*g\n\rMarkLabelType\x12\x1f\n\x1bMARK_LABEL_TYPE_SINGLE_TEXT\x10\x00\x12\x19\n\x15MARK_LABEL_TYPE_IMAGE\x10\x01\x12\x1a\n\x16MARK_LABEL_TYPE_LOTTIE\x10\x02\x62\x06proto3'
)

_MARKLABELTYPE = _descriptor.EnumDescriptor(
  name='MarkLabelType',
  full_name='com.tencent.qqlive.protocol.pb.MarkLabelType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MARK_LABEL_TYPE_SINGLE_TEXT', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MARK_LABEL_TYPE_IMAGE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MARK_LABEL_TYPE_LOTTIE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=63,
  serialized_end=166,
)
_sym_db.RegisterEnumDescriptor(_MARKLABELTYPE)

MarkLabelType = enum_type_wrapper.EnumTypeWrapper(_MARKLABELTYPE)
MARK_LABEL_TYPE_SINGLE_TEXT = 0
MARK_LABEL_TYPE_IMAGE = 1
MARK_LABEL_TYPE_LOTTIE = 2


DESCRIPTOR.enum_types_by_name['MarkLabelType'] = _MARKLABELTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
