# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pyproto/MarkLabelList.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pyproto import MarkLabel_pb2 as pyproto_dot_MarkLabel__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pyproto/MarkLabelList.proto',
  package='com.tencent.qqlive.protocol.pb',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1bpyproto/MarkLabelList.proto\x12\x1e\x63om.tencent.qqlive.protocol.pb\x1a\x17pyproto/MarkLabel.proto\"S\n\rMarkLabelList\x12\x42\n\x0fmark_label_list\x18\x01 \x03(\x0b\x32).com.tencent.qqlive.protocol.pb.MarkLabelb\x06proto3'
  ,
  dependencies=[pyproto_dot_MarkLabel__pb2.DESCRIPTOR,])




_MARKLABELLIST = _descriptor.Descriptor(
  name='MarkLabelList',
  full_name='com.tencent.qqlive.protocol.pb.MarkLabelList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mark_label_list', full_name='com.tencent.qqlive.protocol.pb.MarkLabelList.mark_label_list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=171,
)

_MARKLABELLIST.fields_by_name['mark_label_list'].message_type = pyproto_dot_MarkLabel__pb2._MARKLABEL
DESCRIPTOR.message_types_by_name['MarkLabelList'] = _MARKLABELLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MarkLabelList = _reflection.GeneratedProtocolMessageType('MarkLabelList', (_message.Message,), {
  'DESCRIPTOR' : _MARKLABELLIST,
  '__module__' : 'pyproto.MarkLabelList_pb2'
  # @@protoc_insertion_point(class_scope:com.tencent.qqlive.protocol.pb.MarkLabelList)
  })
_sym_db.RegisterMessage(MarkLabelList)


# @@protoc_insertion_point(module_scope)
