# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pyproto/MarkLabel.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pyproto import MarkLabelType_pb2 as pyproto_dot_MarkLabelType__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pyproto/MarkLabel.proto',
  package='com.tencent.qqlive.protocol.pb',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17pyproto/MarkLabel.proto\x12\x1e\x63om.tencent.qqlive.protocol.pb\x1a\x1bpyproto/MarkLabelType.proto\"\xe8\x01\n\tMarkLabel\x12K\n\x0fmark_label_type\x18\x01 \x01(\x0e\x32-.com.tencent.qqlive.protocol.pb.MarkLabelTypeH\x00\x88\x01\x01\x12\x15\n\x08position\x18\x02 \x01(\x05H\x01\x88\x01\x01\x12\x17\n\nprime_text\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x1b\n\x0emark_image_url\x18\x04 \x01(\tH\x03\x88\x01\x01\x42\x12\n\x10_mark_label_typeB\x0b\n\t_positionB\r\n\x0b_prime_textB\x11\n\x0f_mark_image_urlb\x06proto3'
  ,
  dependencies=[pyproto_dot_MarkLabelType__pb2.DESCRIPTOR,])




_MARKLABEL = _descriptor.Descriptor(
  name='MarkLabel',
  full_name='com.tencent.qqlive.protocol.pb.MarkLabel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mark_label_type', full_name='com.tencent.qqlive.protocol.pb.MarkLabel.mark_label_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='position', full_name='com.tencent.qqlive.protocol.pb.MarkLabel.position', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='prime_text', full_name='com.tencent.qqlive.protocol.pb.MarkLabel.prime_text', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mark_image_url', full_name='com.tencent.qqlive.protocol.pb.MarkLabel.mark_image_url', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_mark_label_type', full_name='com.tencent.qqlive.protocol.pb.MarkLabel._mark_label_type',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_position', full_name='com.tencent.qqlive.protocol.pb.MarkLabel._position',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_prime_text', full_name='com.tencent.qqlive.protocol.pb.MarkLabel._prime_text',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_mark_image_url', full_name='com.tencent.qqlive.protocol.pb.MarkLabel._mark_image_url',
      index=3, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=89,
  serialized_end=321,
)

_MARKLABEL.fields_by_name['mark_label_type'].enum_type = pyproto_dot_MarkLabelType__pb2._MARKLABELTYPE
_MARKLABEL.oneofs_by_name['_mark_label_type'].fields.append(
  _MARKLABEL.fields_by_name['mark_label_type'])
_MARKLABEL.fields_by_name['mark_label_type'].containing_oneof = _MARKLABEL.oneofs_by_name['_mark_label_type']
_MARKLABEL.oneofs_by_name['_position'].fields.append(
  _MARKLABEL.fields_by_name['position'])
_MARKLABEL.fields_by_name['position'].containing_oneof = _MARKLABEL.oneofs_by_name['_position']
_MARKLABEL.oneofs_by_name['_prime_text'].fields.append(
  _MARKLABEL.fields_by_name['prime_text'])
_MARKLABEL.fields_by_name['prime_text'].containing_oneof = _MARKLABEL.oneofs_by_name['_prime_text']
_MARKLABEL.oneofs_by_name['_mark_image_url'].fields.append(
  _MARKLABEL.fields_by_name['mark_image_url'])
_MARKLABEL.fields_by_name['mark_image_url'].containing_oneof = _MARKLABEL.oneofs_by_name['_mark_image_url']
DESCRIPTOR.message_types_by_name['MarkLabel'] = _MARKLABEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MarkLabel = _reflection.GeneratedProtocolMessageType('MarkLabel', (_message.Message,), {
  'DESCRIPTOR' : _MARKLABEL,
  '__module__' : 'pyproto.MarkLabel_pb2'
  # @@protoc_insertion_point(class_scope:com.tencent.qqlive.protocol.pb.MarkLabel)
  })
_sym_db.RegisterMessage(MarkLabel)


# @@protoc_insertion_point(module_scope)
