# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pyproto/Section.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pyproto import Operation_pb2 as pyproto_dot_Operation__pb2
from pyproto import CSSStruct_pb2 as pyproto_dot_CSSStruct__pb2
from pyproto import ExtraData_pb2 as pyproto_dot_ExtraData__pb2
from pyproto import SectionType_pb2 as pyproto_dot_SectionType__pb2
from pyproto import BlockList_pb2 as pyproto_dot_BlockList__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pyproto/Section.proto',
  package='com.tencent.qqlive.protocol.pb',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15pyproto/Section.proto\x12\x1e\x63om.tencent.qqlive.protocol.pb\x1a\x17pyproto/Operation.proto\x1a\x17pyproto/CSSStruct.proto\x1a\x17pyproto/ExtraData.proto\x1a\x19pyproto/SectionType.proto\x1a\x17pyproto/BlockList.proto\"\xff\x07\n\x07Section\x12\x46\n\x0csection_type\x18\x01 \x01(\x0e\x32+.com.tencent.qqlive.protocol.pb.SectionTypeH\x00\x88\x01\x01\x12 \n\x13section_layout_type\x18\x02 \x01(\x05H\x01\x88\x01\x01\x12\x42\n\ncss_struct\x18\x03 \x01(\x0b\x32).com.tencent.qqlive.protocol.pb.CSSStructH\x02\x88\x01\x01\x12\x17\n\nsection_id\x18\x04 \x01(\tH\x03\x88\x01\x01\x12\x42\n\nblock_list\x18\x05 \x01(\x0b\x32).com.tencent.qqlive.protocol.pb.BlockListH\x04\x88\x01\x01\x12\x46\n\x0e\x65xtra_any_data\x18\x07 \x01(\x0b\x32).com.tencent.qqlive.protocol.pb.ExtraDataH\x05\x88\x01\x01\x12L\n\x0breport_dict\x18\x08 \x03(\x0b\x32\x37.com.tencent.qqlive.protocol.pb.Section.ReportDictEntry\x12R\n\x0especial_blocks\x18\t \x03(\x0b\x32:.com.tencent.qqlive.protocol.pb.Section.SpecialBlocksEntry\x12P\n\roperation_map\x18\n \x03(\x0b\x32\x39.com.tencent.qqlive.protocol.pb.Section.OperationMapEntry\x12\x15\n\x08merge_id\x18\x0b \x01(\tH\x06\x88\x01\x01\x12\x1a\n\rblock_related\x18\x0c \x01(\x08H\x07\x88\x01\x01\x1a\x31\n\x0fReportDictEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a_\n\x12SpecialBlocksEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x38\n\x05value\x18\x02 \x01(\x0b\x32).com.tencent.qqlive.protocol.pb.BlockList:\x02\x38\x01\x1a^\n\x11OperationMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x38\n\x05value\x18\x02 \x01(\x0b\x32).com.tencent.qqlive.protocol.pb.Operation:\x02\x38\x01\x42\x0f\n\r_section_typeB\x16\n\x14_section_layout_typeB\r\n\x0b_css_structB\r\n\x0b_section_idB\r\n\x0b_block_listB\x11\n\x0f_extra_any_dataB\x0b\n\t_merge_idB\x10\n\x0e_block_relatedb\x06proto3'
  ,
  dependencies=[pyproto_dot_Operation__pb2.DESCRIPTOR,pyproto_dot_CSSStruct__pb2.DESCRIPTOR,pyproto_dot_ExtraData__pb2.DESCRIPTOR,pyproto_dot_SectionType__pb2.DESCRIPTOR,pyproto_dot_BlockList__pb2.DESCRIPTOR,])




_SECTION_REPORTDICTENTRY = _descriptor.Descriptor(
  name='ReportDictEntry',
  full_name='com.tencent.qqlive.protocol.pb.Section.ReportDictEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='com.tencent.qqlive.protocol.pb.Section.ReportDictEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='com.tencent.qqlive.protocol.pb.Section.ReportDictEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=830,
  serialized_end=879,
)

_SECTION_SPECIALBLOCKSENTRY = _descriptor.Descriptor(
  name='SpecialBlocksEntry',
  full_name='com.tencent.qqlive.protocol.pb.Section.SpecialBlocksEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='com.tencent.qqlive.protocol.pb.Section.SpecialBlocksEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='com.tencent.qqlive.protocol.pb.Section.SpecialBlocksEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=881,
  serialized_end=976,
)

_SECTION_OPERATIONMAPENTRY = _descriptor.Descriptor(
  name='OperationMapEntry',
  full_name='com.tencent.qqlive.protocol.pb.Section.OperationMapEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='com.tencent.qqlive.protocol.pb.Section.OperationMapEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='com.tencent.qqlive.protocol.pb.Section.OperationMapEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=978,
  serialized_end=1072,
)

_SECTION = _descriptor.Descriptor(
  name='Section',
  full_name='com.tencent.qqlive.protocol.pb.Section',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='section_type', full_name='com.tencent.qqlive.protocol.pb.Section.section_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='section_layout_type', full_name='com.tencent.qqlive.protocol.pb.Section.section_layout_type', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='css_struct', full_name='com.tencent.qqlive.protocol.pb.Section.css_struct', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='section_id', full_name='com.tencent.qqlive.protocol.pb.Section.section_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='block_list', full_name='com.tencent.qqlive.protocol.pb.Section.block_list', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='extra_any_data', full_name='com.tencent.qqlive.protocol.pb.Section.extra_any_data', index=5,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='report_dict', full_name='com.tencent.qqlive.protocol.pb.Section.report_dict', index=6,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='special_blocks', full_name='com.tencent.qqlive.protocol.pb.Section.special_blocks', index=7,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='operation_map', full_name='com.tencent.qqlive.protocol.pb.Section.operation_map', index=8,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='merge_id', full_name='com.tencent.qqlive.protocol.pb.Section.merge_id', index=9,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='block_related', full_name='com.tencent.qqlive.protocol.pb.Section.block_related', index=10,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_SECTION_REPORTDICTENTRY, _SECTION_SPECIALBLOCKSENTRY, _SECTION_OPERATIONMAPENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_section_type', full_name='com.tencent.qqlive.protocol.pb.Section._section_type',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_section_layout_type', full_name='com.tencent.qqlive.protocol.pb.Section._section_layout_type',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_css_struct', full_name='com.tencent.qqlive.protocol.pb.Section._css_struct',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_section_id', full_name='com.tencent.qqlive.protocol.pb.Section._section_id',
      index=3, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_block_list', full_name='com.tencent.qqlive.protocol.pb.Section._block_list',
      index=4, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_extra_any_data', full_name='com.tencent.qqlive.protocol.pb.Section._extra_any_data',
      index=5, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_merge_id', full_name='com.tencent.qqlive.protocol.pb.Section._merge_id',
      index=6, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_block_related', full_name='com.tencent.qqlive.protocol.pb.Section._block_related',
      index=7, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=185,
  serialized_end=1208,
)

_SECTION_REPORTDICTENTRY.containing_type = _SECTION
_SECTION_SPECIALBLOCKSENTRY.fields_by_name['value'].message_type = pyproto_dot_BlockList__pb2._BLOCKLIST
_SECTION_SPECIALBLOCKSENTRY.containing_type = _SECTION
_SECTION_OPERATIONMAPENTRY.fields_by_name['value'].message_type = pyproto_dot_Operation__pb2._OPERATION
_SECTION_OPERATIONMAPENTRY.containing_type = _SECTION
_SECTION.fields_by_name['section_type'].enum_type = pyproto_dot_SectionType__pb2._SECTIONTYPE
_SECTION.fields_by_name['css_struct'].message_type = pyproto_dot_CSSStruct__pb2._CSSSTRUCT
_SECTION.fields_by_name['block_list'].message_type = pyproto_dot_BlockList__pb2._BLOCKLIST
_SECTION.fields_by_name['extra_any_data'].message_type = pyproto_dot_ExtraData__pb2._EXTRADATA
_SECTION.fields_by_name['report_dict'].message_type = _SECTION_REPORTDICTENTRY
_SECTION.fields_by_name['special_blocks'].message_type = _SECTION_SPECIALBLOCKSENTRY
_SECTION.fields_by_name['operation_map'].message_type = _SECTION_OPERATIONMAPENTRY
_SECTION.oneofs_by_name['_section_type'].fields.append(
  _SECTION.fields_by_name['section_type'])
_SECTION.fields_by_name['section_type'].containing_oneof = _SECTION.oneofs_by_name['_section_type']
_SECTION.oneofs_by_name['_section_layout_type'].fields.append(
  _SECTION.fields_by_name['section_layout_type'])
_SECTION.fields_by_name['section_layout_type'].containing_oneof = _SECTION.oneofs_by_name['_section_layout_type']
_SECTION.oneofs_by_name['_css_struct'].fields.append(
  _SECTION.fields_by_name['css_struct'])
_SECTION.fields_by_name['css_struct'].containing_oneof = _SECTION.oneofs_by_name['_css_struct']
_SECTION.oneofs_by_name['_section_id'].fields.append(
  _SECTION.fields_by_name['section_id'])
_SECTION.fields_by_name['section_id'].containing_oneof = _SECTION.oneofs_by_name['_section_id']
_SECTION.oneofs_by_name['_block_list'].fields.append(
  _SECTION.fields_by_name['block_list'])
_SECTION.fields_by_name['block_list'].containing_oneof = _SECTION.oneofs_by_name['_block_list']
_SECTION.oneofs_by_name['_extra_any_data'].fields.append(
  _SECTION.fields_by_name['extra_any_data'])
_SECTION.fields_by_name['extra_any_data'].containing_oneof = _SECTION.oneofs_by_name['_extra_any_data']
_SECTION.oneofs_by_name['_merge_id'].fields.append(
  _SECTION.fields_by_name['merge_id'])
_SECTION.fields_by_name['merge_id'].containing_oneof = _SECTION.oneofs_by_name['_merge_id']
_SECTION.oneofs_by_name['_block_related'].fields.append(
  _SECTION.fields_by_name['block_related'])
_SECTION.fields_by_name['block_related'].containing_oneof = _SECTION.oneofs_by_name['_block_related']
DESCRIPTOR.message_types_by_name['Section'] = _SECTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Section = _reflection.GeneratedProtocolMessageType('Section', (_message.Message,), {

  'ReportDictEntry' : _reflection.GeneratedProtocolMessageType('ReportDictEntry', (_message.Message,), {
    'DESCRIPTOR' : _SECTION_REPORTDICTENTRY,
    '__module__' : 'pyproto.Section_pb2'
    # @@protoc_insertion_point(class_scope:com.tencent.qqlive.protocol.pb.Section.ReportDictEntry)
    })
  ,

  'SpecialBlocksEntry' : _reflection.GeneratedProtocolMessageType('SpecialBlocksEntry', (_message.Message,), {
    'DESCRIPTOR' : _SECTION_SPECIALBLOCKSENTRY,
    '__module__' : 'pyproto.Section_pb2'
    # @@protoc_insertion_point(class_scope:com.tencent.qqlive.protocol.pb.Section.SpecialBlocksEntry)
    })
  ,

  'OperationMapEntry' : _reflection.GeneratedProtocolMessageType('OperationMapEntry', (_message.Message,), {
    'DESCRIPTOR' : _SECTION_OPERATIONMAPENTRY,
    '__module__' : 'pyproto.Section_pb2'
    # @@protoc_insertion_point(class_scope:com.tencent.qqlive.protocol.pb.Section.OperationMapEntry)
    })
  ,
  'DESCRIPTOR' : _SECTION,
  '__module__' : 'pyproto.Section_pb2'
  # @@protoc_insertion_point(class_scope:com.tencent.qqlive.protocol.pb.Section)
  })
_sym_db.RegisterMessage(Section)
_sym_db.RegisterMessage(Section.ReportDictEntry)
_sym_db.RegisterMessage(Section.SpecialBlocksEntry)
_sym_db.RegisterMessage(Section.OperationMapEntry)


_SECTION_REPORTDICTENTRY._options = None
_SECTION_SPECIALBLOCKSENTRY._options = None
_SECTION_OPERATIONMAPENTRY._options = None
# @@protoc_insertion_point(module_scope)
