# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pyproto/tbclient.ThemeBgProp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pyproto/tbclient.ThemeBgProp.proto',
  package='tbclient',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\"pyproto/tbclient.ThemeBgProp.proto\x12\x08tbclient\"\xa5\x03\n\x0bThemeBgProp\x12\x15\n\x08props_id\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x12\n\x05title\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x18\n\x0b\x64\x65scription\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x18\n\x0b\x65xample_url\x18\x04 \x01(\tH\x03\x88\x01\x01\x12\x17\n\npermission\x18\x05 \x01(\tH\x04\x88\x01\x01\x12\x1c\n\x0fprops_state_img\x18\x06 \x01(\tH\x05\x88\x01\x01\x12\x13\n\x06in_use\x18\x07 \x01(\rH\x06\x88\x01\x01\x12\x1c\n\x0f\x66ree_user_level\x18\x08 \x01(\x05H\x07\x88\x01\x01\x12\x19\n\x0c\x61\x63tivity_url\x18\t \x01(\tH\x08\x88\x01\x01\x12\x18\n\x0bis_finished\x18\n \x01(\x05H\t\x88\x01\x01\x42\x0b\n\t_props_idB\x08\n\x06_titleB\x0e\n\x0c_descriptionB\x0e\n\x0c_example_urlB\r\n\x0b_permissionB\x12\n\x10_props_state_imgB\t\n\x07_in_useB\x12\n\x10_free_user_levelB\x0f\n\r_activity_urlB\x0e\n\x0c_is_finishedb\x06proto3'
)




_THEMEBGPROP = _descriptor.Descriptor(
  name='ThemeBgProp',
  full_name='tbclient.ThemeBgProp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='props_id', full_name='tbclient.ThemeBgProp.props_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='title', full_name='tbclient.ThemeBgProp.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='tbclient.ThemeBgProp.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='example_url', full_name='tbclient.ThemeBgProp.example_url', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='permission', full_name='tbclient.ThemeBgProp.permission', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='props_state_img', full_name='tbclient.ThemeBgProp.props_state_img', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='in_use', full_name='tbclient.ThemeBgProp.in_use', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='free_user_level', full_name='tbclient.ThemeBgProp.free_user_level', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='activity_url', full_name='tbclient.ThemeBgProp.activity_url', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_finished', full_name='tbclient.ThemeBgProp.is_finished', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_props_id', full_name='tbclient.ThemeBgProp._props_id',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_title', full_name='tbclient.ThemeBgProp._title',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_description', full_name='tbclient.ThemeBgProp._description',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_example_url', full_name='tbclient.ThemeBgProp._example_url',
      index=3, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_permission', full_name='tbclient.ThemeBgProp._permission',
      index=4, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_props_state_img', full_name='tbclient.ThemeBgProp._props_state_img',
      index=5, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_in_use', full_name='tbclient.ThemeBgProp._in_use',
      index=6, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_free_user_level', full_name='tbclient.ThemeBgProp._free_user_level',
      index=7, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_activity_url', full_name='tbclient.ThemeBgProp._activity_url',
      index=8, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_is_finished', full_name='tbclient.ThemeBgProp._is_finished',
      index=9, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=49,
  serialized_end=470,
)

_THEMEBGPROP.oneofs_by_name['_props_id'].fields.append(
  _THEMEBGPROP.fields_by_name['props_id'])
_THEMEBGPROP.fields_by_name['props_id'].containing_oneof = _THEMEBGPROP.oneofs_by_name['_props_id']
_THEMEBGPROP.oneofs_by_name['_title'].fields.append(
  _THEMEBGPROP.fields_by_name['title'])
_THEMEBGPROP.fields_by_name['title'].containing_oneof = _THEMEBGPROP.oneofs_by_name['_title']
_THEMEBGPROP.oneofs_by_name['_description'].fields.append(
  _THEMEBGPROP.fields_by_name['description'])
_THEMEBGPROP.fields_by_name['description'].containing_oneof = _THEMEBGPROP.oneofs_by_name['_description']
_THEMEBGPROP.oneofs_by_name['_example_url'].fields.append(
  _THEMEBGPROP.fields_by_name['example_url'])
_THEMEBGPROP.fields_by_name['example_url'].containing_oneof = _THEMEBGPROP.oneofs_by_name['_example_url']
_THEMEBGPROP.oneofs_by_name['_permission'].fields.append(
  _THEMEBGPROP.fields_by_name['permission'])
_THEMEBGPROP.fields_by_name['permission'].containing_oneof = _THEMEBGPROP.oneofs_by_name['_permission']
_THEMEBGPROP.oneofs_by_name['_props_state_img'].fields.append(
  _THEMEBGPROP.fields_by_name['props_state_img'])
_THEMEBGPROP.fields_by_name['props_state_img'].containing_oneof = _THEMEBGPROP.oneofs_by_name['_props_state_img']
_THEMEBGPROP.oneofs_by_name['_in_use'].fields.append(
  _THEMEBGPROP.fields_by_name['in_use'])
_THEMEBGPROP.fields_by_name['in_use'].containing_oneof = _THEMEBGPROP.oneofs_by_name['_in_use']
_THEMEBGPROP.oneofs_by_name['_free_user_level'].fields.append(
  _THEMEBGPROP.fields_by_name['free_user_level'])
_THEMEBGPROP.fields_by_name['free_user_level'].containing_oneof = _THEMEBGPROP.oneofs_by_name['_free_user_level']
_THEMEBGPROP.oneofs_by_name['_activity_url'].fields.append(
  _THEMEBGPROP.fields_by_name['activity_url'])
_THEMEBGPROP.fields_by_name['activity_url'].containing_oneof = _THEMEBGPROP.oneofs_by_name['_activity_url']
_THEMEBGPROP.oneofs_by_name['_is_finished'].fields.append(
  _THEMEBGPROP.fields_by_name['is_finished'])
_THEMEBGPROP.fields_by_name['is_finished'].containing_oneof = _THEMEBGPROP.oneofs_by_name['_is_finished']
DESCRIPTOR.message_types_by_name['ThemeBgProp'] = _THEMEBGPROP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ThemeBgProp = _reflection.GeneratedProtocolMessageType('ThemeBgProp', (_message.Message,), {
  'DESCRIPTOR' : _THEMEBGPROP,
  '__module__' : 'pyproto.tbclient.ThemeBgProp_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.ThemeBgProp)
  })
_sym_db.RegisterMessage(ThemeBgProp)


# @@protoc_insertion_point(module_scope)
