# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pyproto/tbclient.ThemeRecommand.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pyproto/tbclient.ThemeRecommand.proto',
  package='tbclient',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n%pyproto/tbclient.ThemeRecommand.proto\x12\x08tbclient\"\xa2\x01\n\x0eThemeRecommand\x12\x11\n\x04icon\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x15\n\x08tip_text\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x17\n\nbutton_url\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x18\n\x0b\x62utton_text\x18\x04 \x01(\tH\x03\x88\x01\x01\x42\x07\n\x05_iconB\x0b\n\t_tip_textB\r\n\x0b_button_urlB\x0e\n\x0c_button_textb\x06proto3'
)




_THEMERECOMMAND = _descriptor.Descriptor(
  name='ThemeRecommand',
  full_name='tbclient.ThemeRecommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='icon', full_name='tbclient.ThemeRecommand.icon', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tip_text', full_name='tbclient.ThemeRecommand.tip_text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='button_url', full_name='tbclient.ThemeRecommand.button_url', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='button_text', full_name='tbclient.ThemeRecommand.button_text', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_icon', full_name='tbclient.ThemeRecommand._icon',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_tip_text', full_name='tbclient.ThemeRecommand._tip_text',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_button_url', full_name='tbclient.ThemeRecommand._button_url',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_button_text', full_name='tbclient.ThemeRecommand._button_text',
      index=3, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=52,
  serialized_end=214,
)

_THEMERECOMMAND.oneofs_by_name['_icon'].fields.append(
  _THEMERECOMMAND.fields_by_name['icon'])
_THEMERECOMMAND.fields_by_name['icon'].containing_oneof = _THEMERECOMMAND.oneofs_by_name['_icon']
_THEMERECOMMAND.oneofs_by_name['_tip_text'].fields.append(
  _THEMERECOMMAND.fields_by_name['tip_text'])
_THEMERECOMMAND.fields_by_name['tip_text'].containing_oneof = _THEMERECOMMAND.oneofs_by_name['_tip_text']
_THEMERECOMMAND.oneofs_by_name['_button_url'].fields.append(
  _THEMERECOMMAND.fields_by_name['button_url'])
_THEMERECOMMAND.fields_by_name['button_url'].containing_oneof = _THEMERECOMMAND.oneofs_by_name['_button_url']
_THEMERECOMMAND.oneofs_by_name['_button_text'].fields.append(
  _THEMERECOMMAND.fields_by_name['button_text'])
_THEMERECOMMAND.fields_by_name['button_text'].containing_oneof = _THEMERECOMMAND.oneofs_by_name['_button_text']
DESCRIPTOR.message_types_by_name['ThemeRecommand'] = _THEMERECOMMAND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ThemeRecommand = _reflection.GeneratedProtocolMessageType('ThemeRecommand', (_message.Message,), {
  'DESCRIPTOR' : _THEMERECOMMAND,
  '__module__' : 'pyproto.tbclient.ThemeRecommand_pb2'
  # @@protoc_insertion_point(class_scope:tbclient.ThemeRecommand)
  })
_sym_db.RegisterMessage(ThemeRecommand)


# @@protoc_insertion_point(module_scope)
