# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pyproto/com.bapis.bilibili.app.card.v1.AdInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pyproto.com.bapis.bilibili.app.card.v1 import CreativeContent_pb2 as pyproto_dot_com_dot_bapis_dot_bilibili_dot_app_dot_card_dot_v1_dot_CreativeContent__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pyproto/com.bapis.bilibili.app.card.v1.AdInfo.proto',
  package='com.bapis.bilibili.app.card.v1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n3pyproto/com.bapis.bilibili.app.card.v1.AdInfo.proto\x12\x1e\x63om.bapis.bilibili.app.card.v1\x1a<pyproto/com.bapis.bilibili.app.card.v1.CreativeContent.proto\x1a\x19google/protobuf/any.proto\"\xab\x05\n\x06\x41\x64Info\x12\x18\n\x0b\x63reative_id\x18\x01 \x01(\x03H\x00\x88\x01\x01\x12\x1a\n\rcreative_type\x18\x02 \x01(\x05H\x01\x88\x01\x01\x12\x16\n\tcard_type\x18\x03 \x01(\x05H\x02\x88\x01\x01\x12N\n\x10\x63reative_content\x18\x04 \x01(\x0b\x32/.com.bapis.bilibili.app.card.v1.CreativeContentH\x03\x88\x01\x01\x12\x12\n\x05\x61\x64_cb\x18\x05 \x01(\tH\x04\x88\x01\x01\x12\x15\n\x08resource\x18\x06 \x01(\x03H\x05\x88\x01\x01\x12\x13\n\x06source\x18\x07 \x01(\x05H\x06\x88\x01\x01\x12\x17\n\nrequest_id\x18\x08 \x01(\tH\x07\x88\x01\x01\x12\x12\n\x05is_ad\x18\t \x01(\x08H\x08\x88\x01\x01\x12\x14\n\x07\x63m_mark\x18\n \x01(\x03H\t\x88\x01\x01\x12\x12\n\x05index\x18\x0b \x01(\x05H\n\x88\x01\x01\x12\x16\n\tis_ad_loc\x18\x0c \x01(\x08H\x0b\x88\x01\x01\x12\x17\n\ncard_index\x18\r \x01(\x05H\x0c\x88\x01\x01\x12\x16\n\tclient_ip\x18\x0e \x01(\tH\r\x88\x01\x01\x12(\n\x05\x65xtra\x18\x0f \x01(\x0b\x32\x14.google.protobuf.AnyH\x0e\x88\x01\x01\x12\x1b\n\x0e\x63reative_style\x18\x10 \x01(\x05H\x0f\x88\x01\x01\x42\x0e\n\x0c_creative_idB\x10\n\x0e_creative_typeB\x0c\n\n_card_typeB\x13\n\x11_creative_contentB\x08\n\x06_ad_cbB\x0b\n\t_resourceB\t\n\x07_sourceB\r\n\x0b_request_idB\x08\n\x06_is_adB\n\n\x08_cm_markB\x08\n\x06_indexB\x0c\n\n_is_ad_locB\r\n\x0b_card_indexB\x0c\n\n_client_ipB\x08\n\x06_extraB\x11\n\x0f_creative_styleb\x06proto3'
  ,
  dependencies=[pyproto_dot_com_dot_bapis_dot_bilibili_dot_app_dot_card_dot_v1_dot_CreativeContent__pb2.DESCRIPTOR,google_dot_protobuf_dot_any__pb2.DESCRIPTOR,])




_ADINFO = _descriptor.Descriptor(
  name='AdInfo',
  full_name='com.bapis.bilibili.app.card.v1.AdInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='creative_id', full_name='com.bapis.bilibili.app.card.v1.AdInfo.creative_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='creative_type', full_name='com.bapis.bilibili.app.card.v1.AdInfo.creative_type', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='card_type', full_name='com.bapis.bilibili.app.card.v1.AdInfo.card_type', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='creative_content', full_name='com.bapis.bilibili.app.card.v1.AdInfo.creative_content', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ad_cb', full_name='com.bapis.bilibili.app.card.v1.AdInfo.ad_cb', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='resource', full_name='com.bapis.bilibili.app.card.v1.AdInfo.resource', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='source', full_name='com.bapis.bilibili.app.card.v1.AdInfo.source', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='request_id', full_name='com.bapis.bilibili.app.card.v1.AdInfo.request_id', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_ad', full_name='com.bapis.bilibili.app.card.v1.AdInfo.is_ad', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cm_mark', full_name='com.bapis.bilibili.app.card.v1.AdInfo.cm_mark', index=9,
      number=10, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='index', full_name='com.bapis.bilibili.app.card.v1.AdInfo.index', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_ad_loc', full_name='com.bapis.bilibili.app.card.v1.AdInfo.is_ad_loc', index=11,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='card_index', full_name='com.bapis.bilibili.app.card.v1.AdInfo.card_index', index=12,
      number=13, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='client_ip', full_name='com.bapis.bilibili.app.card.v1.AdInfo.client_ip', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='extra', full_name='com.bapis.bilibili.app.card.v1.AdInfo.extra', index=14,
      number=15, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='creative_style', full_name='com.bapis.bilibili.app.card.v1.AdInfo.creative_style', index=15,
      number=16, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_creative_id', full_name='com.bapis.bilibili.app.card.v1.AdInfo._creative_id',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_creative_type', full_name='com.bapis.bilibili.app.card.v1.AdInfo._creative_type',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_card_type', full_name='com.bapis.bilibili.app.card.v1.AdInfo._card_type',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_creative_content', full_name='com.bapis.bilibili.app.card.v1.AdInfo._creative_content',
      index=3, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_ad_cb', full_name='com.bapis.bilibili.app.card.v1.AdInfo._ad_cb',
      index=4, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_resource', full_name='com.bapis.bilibili.app.card.v1.AdInfo._resource',
      index=5, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_source', full_name='com.bapis.bilibili.app.card.v1.AdInfo._source',
      index=6, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_request_id', full_name='com.bapis.bilibili.app.card.v1.AdInfo._request_id',
      index=7, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_is_ad', full_name='com.bapis.bilibili.app.card.v1.AdInfo._is_ad',
      index=8, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_cm_mark', full_name='com.bapis.bilibili.app.card.v1.AdInfo._cm_mark',
      index=9, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_index', full_name='com.bapis.bilibili.app.card.v1.AdInfo._index',
      index=10, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_is_ad_loc', full_name='com.bapis.bilibili.app.card.v1.AdInfo._is_ad_loc',
      index=11, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_card_index', full_name='com.bapis.bilibili.app.card.v1.AdInfo._card_index',
      index=12, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_client_ip', full_name='com.bapis.bilibili.app.card.v1.AdInfo._client_ip',
      index=13, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_extra', full_name='com.bapis.bilibili.app.card.v1.AdInfo._extra',
      index=14, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_creative_style', full_name='com.bapis.bilibili.app.card.v1.AdInfo._creative_style',
      index=15, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=177,
  serialized_end=860,
)

_ADINFO.fields_by_name['creative_content'].message_type = pyproto_dot_com_dot_bapis_dot_bilibili_dot_app_dot_card_dot_v1_dot_CreativeContent__pb2._CREATIVECONTENT
_ADINFO.fields_by_name['extra'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_ADINFO.oneofs_by_name['_creative_id'].fields.append(
  _ADINFO.fields_by_name['creative_id'])
_ADINFO.fields_by_name['creative_id'].containing_oneof = _ADINFO.oneofs_by_name['_creative_id']
_ADINFO.oneofs_by_name['_creative_type'].fields.append(
  _ADINFO.fields_by_name['creative_type'])
_ADINFO.fields_by_name['creative_type'].containing_oneof = _ADINFO.oneofs_by_name['_creative_type']
_ADINFO.oneofs_by_name['_card_type'].fields.append(
  _ADINFO.fields_by_name['card_type'])
_ADINFO.fields_by_name['card_type'].containing_oneof = _ADINFO.oneofs_by_name['_card_type']
_ADINFO.oneofs_by_name['_creative_content'].fields.append(
  _ADINFO.fields_by_name['creative_content'])
_ADINFO.fields_by_name['creative_content'].containing_oneof = _ADINFO.oneofs_by_name['_creative_content']
_ADINFO.oneofs_by_name['_ad_cb'].fields.append(
  _ADINFO.fields_by_name['ad_cb'])
_ADINFO.fields_by_name['ad_cb'].containing_oneof = _ADINFO.oneofs_by_name['_ad_cb']
_ADINFO.oneofs_by_name['_resource'].fields.append(
  _ADINFO.fields_by_name['resource'])
_ADINFO.fields_by_name['resource'].containing_oneof = _ADINFO.oneofs_by_name['_resource']
_ADINFO.oneofs_by_name['_source'].fields.append(
  _ADINFO.fields_by_name['source'])
_ADINFO.fields_by_name['source'].containing_oneof = _ADINFO.oneofs_by_name['_source']
_ADINFO.oneofs_by_name['_request_id'].fields.append(
  _ADINFO.fields_by_name['request_id'])
_ADINFO.fields_by_name['request_id'].containing_oneof = _ADINFO.oneofs_by_name['_request_id']
_ADINFO.oneofs_by_name['_is_ad'].fields.append(
  _ADINFO.fields_by_name['is_ad'])
_ADINFO.fields_by_name['is_ad'].containing_oneof = _ADINFO.oneofs_by_name['_is_ad']
_ADINFO.oneofs_by_name['_cm_mark'].fields.append(
  _ADINFO.fields_by_name['cm_mark'])
_ADINFO.fields_by_name['cm_mark'].containing_oneof = _ADINFO.oneofs_by_name['_cm_mark']
_ADINFO.oneofs_by_name['_index'].fields.append(
  _ADINFO.fields_by_name['index'])
_ADINFO.fields_by_name['index'].containing_oneof = _ADINFO.oneofs_by_name['_index']
_ADINFO.oneofs_by_name['_is_ad_loc'].fields.append(
  _ADINFO.fields_by_name['is_ad_loc'])
_ADINFO.fields_by_name['is_ad_loc'].containing_oneof = _ADINFO.oneofs_by_name['_is_ad_loc']
_ADINFO.oneofs_by_name['_card_index'].fields.append(
  _ADINFO.fields_by_name['card_index'])
_ADINFO.fields_by_name['card_index'].containing_oneof = _ADINFO.oneofs_by_name['_card_index']
_ADINFO.oneofs_by_name['_client_ip'].fields.append(
  _ADINFO.fields_by_name['client_ip'])
_ADINFO.fields_by_name['client_ip'].containing_oneof = _ADINFO.oneofs_by_name['_client_ip']
_ADINFO.oneofs_by_name['_extra'].fields.append(
  _ADINFO.fields_by_name['extra'])
_ADINFO.fields_by_name['extra'].containing_oneof = _ADINFO.oneofs_by_name['_extra']
_ADINFO.oneofs_by_name['_creative_style'].fields.append(
  _ADINFO.fields_by_name['creative_style'])
_ADINFO.fields_by_name['creative_style'].containing_oneof = _ADINFO.oneofs_by_name['_creative_style']
DESCRIPTOR.message_types_by_name['AdInfo'] = _ADINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AdInfo = _reflection.GeneratedProtocolMessageType('AdInfo', (_message.Message,), {
  'DESCRIPTOR' : _ADINFO,
  '__module__' : 'pyproto.com.bapis.bilibili.app.card.v1.AdInfo_pb2'
  # @@protoc_insertion_point(class_scope:com.bapis.bilibili.app.card.v1.AdInfo)
  })
_sym_db.RegisterMessage(AdInfo)


# @@protoc_insertion_point(module_scope)
