# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pyproto/com.bapis.bilibili.app.card.v1.Avatar.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pyproto/com.bapis.bilibili.app.card.v1.Avatar.proto',
  package='com.bapis.bilibili.app.card.v1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n3pyproto/com.bapis.bilibili.app.card.v1.Avatar.proto\x12\x1e\x63om.bapis.bilibili.app.card.v1\"\xc4\x01\n\x06\x41vatar\x12\x12\n\x05\x63over\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x11\n\x04text\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x10\n\x03uri\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x11\n\x04type\x18\x04 \x01(\x05H\x03\x88\x01\x01\x12\x12\n\x05\x65vent\x18\x05 \x01(\tH\x04\x88\x01\x01\x12\x1a\n\rdefalut_cover\x18\x07 \x01(\x05H\x05\x88\x01\x01\x42\x08\n\x06_coverB\x07\n\x05_textB\x06\n\x04_uriB\x07\n\x05_typeB\x08\n\x06_eventB\x10\n\x0e_defalut_coverb\x06proto3'
)




_AVATAR = _descriptor.Descriptor(
  name='Avatar',
  full_name='com.bapis.bilibili.app.card.v1.Avatar',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cover', full_name='com.bapis.bilibili.app.card.v1.Avatar.cover', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='text', full_name='com.bapis.bilibili.app.card.v1.Avatar.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='uri', full_name='com.bapis.bilibili.app.card.v1.Avatar.uri', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='com.bapis.bilibili.app.card.v1.Avatar.type', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='event', full_name='com.bapis.bilibili.app.card.v1.Avatar.event', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='defalut_cover', full_name='com.bapis.bilibili.app.card.v1.Avatar.defalut_cover', index=5,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_cover', full_name='com.bapis.bilibili.app.card.v1.Avatar._cover',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_text', full_name='com.bapis.bilibili.app.card.v1.Avatar._text',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_uri', full_name='com.bapis.bilibili.app.card.v1.Avatar._uri',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_type', full_name='com.bapis.bilibili.app.card.v1.Avatar._type',
      index=3, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_event', full_name='com.bapis.bilibili.app.card.v1.Avatar._event',
      index=4, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_defalut_cover', full_name='com.bapis.bilibili.app.card.v1.Avatar._defalut_cover',
      index=5, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=88,
  serialized_end=284,
)

_AVATAR.oneofs_by_name['_cover'].fields.append(
  _AVATAR.fields_by_name['cover'])
_AVATAR.fields_by_name['cover'].containing_oneof = _AVATAR.oneofs_by_name['_cover']
_AVATAR.oneofs_by_name['_text'].fields.append(
  _AVATAR.fields_by_name['text'])
_AVATAR.fields_by_name['text'].containing_oneof = _AVATAR.oneofs_by_name['_text']
_AVATAR.oneofs_by_name['_uri'].fields.append(
  _AVATAR.fields_by_name['uri'])
_AVATAR.fields_by_name['uri'].containing_oneof = _AVATAR.oneofs_by_name['_uri']
_AVATAR.oneofs_by_name['_type'].fields.append(
  _AVATAR.fields_by_name['type'])
_AVATAR.fields_by_name['type'].containing_oneof = _AVATAR.oneofs_by_name['_type']
_AVATAR.oneofs_by_name['_event'].fields.append(
  _AVATAR.fields_by_name['event'])
_AVATAR.fields_by_name['event'].containing_oneof = _AVATAR.oneofs_by_name['_event']
_AVATAR.oneofs_by_name['_defalut_cover'].fields.append(
  _AVATAR.fields_by_name['defalut_cover'])
_AVATAR.fields_by_name['defalut_cover'].containing_oneof = _AVATAR.oneofs_by_name['_defalut_cover']
DESCRIPTOR.message_types_by_name['Avatar'] = _AVATAR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Avatar = _reflection.GeneratedProtocolMessageType('Avatar', (_message.Message,), {
  'DESCRIPTOR' : _AVATAR,
  '__module__' : 'pyproto.com.bapis.bilibili.app.card.v1.Avatar_pb2'
  # @@protoc_insertion_point(class_scope:com.bapis.bilibili.app.card.v1.Avatar)
  })
_sym_db.RegisterMessage(Avatar)


# @@protoc_insertion_point(module_scope)
