# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pyproto/com.bapis.bilibili.app.card.v1.Bubble.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pyproto/com.bapis.bilibili.app.card.v1.Bubble.proto',
  package='com.bapis.bilibili.app.card.v1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n3pyproto/com.bapis.bilibili.app.card.v1.Bubble.proto\x12\x1e\x63om.bapis.bilibili.app.card.v1\"x\n\x06\x42ubble\x12\x1b\n\x0e\x62ubble_content\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x14\n\x07version\x18\x02 \x01(\x05H\x01\x88\x01\x01\x12\x12\n\x05stime\x18\x03 \x01(\x03H\x02\x88\x01\x01\x42\x11\n\x0f_bubble_contentB\n\n\x08_versionB\x08\n\x06_stimeb\x06proto3'
)




_BUBBLE = _descriptor.Descriptor(
  name='Bubble',
  full_name='com.bapis.bilibili.app.card.v1.Bubble',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='bubble_content', full_name='com.bapis.bilibili.app.card.v1.Bubble.bubble_content', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='version', full_name='com.bapis.bilibili.app.card.v1.Bubble.version', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stime', full_name='com.bapis.bilibili.app.card.v1.Bubble.stime', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_bubble_content', full_name='com.bapis.bilibili.app.card.v1.Bubble._bubble_content',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_version', full_name='com.bapis.bilibili.app.card.v1.Bubble._version',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_stime', full_name='com.bapis.bilibili.app.card.v1.Bubble._stime',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=87,
  serialized_end=207,
)

_BUBBLE.oneofs_by_name['_bubble_content'].fields.append(
  _BUBBLE.fields_by_name['bubble_content'])
_BUBBLE.fields_by_name['bubble_content'].containing_oneof = _BUBBLE.oneofs_by_name['_bubble_content']
_BUBBLE.oneofs_by_name['_version'].fields.append(
  _BUBBLE.fields_by_name['version'])
_BUBBLE.fields_by_name['version'].containing_oneof = _BUBBLE.oneofs_by_name['_version']
_BUBBLE.oneofs_by_name['_stime'].fields.append(
  _BUBBLE.fields_by_name['stime'])
_BUBBLE.fields_by_name['stime'].containing_oneof = _BUBBLE.oneofs_by_name['_stime']
DESCRIPTOR.message_types_by_name['Bubble'] = _BUBBLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Bubble = _reflection.GeneratedProtocolMessageType('Bubble', (_message.Message,), {
  'DESCRIPTOR' : _BUBBLE,
  '__module__' : 'pyproto.com.bapis.bilibili.app.card.v1.Bubble_pb2'
  # @@protoc_insertion_point(class_scope:com.bapis.bilibili.app.card.v1.Bubble)
  })
_sym_db.RegisterMessage(Bubble)


# @@protoc_insertion_point(module_scope)
