# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pyproto/com.bapis.bilibili.app.card.v1.Card.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pyproto.com.bapis.bilibili.app.card.v1 import ThreeItemAllV2_pb2 as pyproto_dot_com_dot_bapis_dot_bilibili_dot_app_dot_card_dot_v1_dot_ThreeItemAllV2__pb2
from pyproto.com.bapis.bilibili.app.card.v1 import LargeCoverV4_pb2 as pyproto_dot_com_dot_bapis_dot_bilibili_dot_app_dot_card_dot_v1_dot_LargeCoverV4__pb2
from pyproto.com.bapis.bilibili.app.card.v1 import PopularTopEntrance_pb2 as pyproto_dot_com_dot_bapis_dot_bilibili_dot_app_dot_card_dot_v1_dot_PopularTopEntrance__pb2
from pyproto.com.bapis.bilibili.app.card.v1 import DynamicHot_pb2 as pyproto_dot_com_dot_bapis_dot_bilibili_dot_app_dot_card_dot_v1_dot_DynamicHot__pb2
from pyproto.com.bapis.bilibili.app.card.v1 import SmallCoverV5_pb2 as pyproto_dot_com_dot_bapis_dot_bilibili_dot_app_dot_card_dot_v1_dot_SmallCoverV5__pb2
from pyproto.com.bapis.bilibili.app.card.v1 import ThreeItemV1_pb2 as pyproto_dot_com_dot_bapis_dot_bilibili_dot_app_dot_card_dot_v1_dot_ThreeItemV1__pb2
from pyproto.com.bapis.bilibili.app.card.v1 import HotTopic_pb2 as pyproto_dot_com_dot_bapis_dot_bilibili_dot_app_dot_card_dot_v1_dot_HotTopic__pb2
from pyproto.com.bapis.bilibili.app.card.v1 import RcmdOneItem_pb2 as pyproto_dot_com_dot_bapis_dot_bilibili_dot_app_dot_card_dot_v1_dot_RcmdOneItem__pb2
from pyproto.com.bapis.bilibili.app.card.v1 import LargeCoverV1_pb2 as pyproto_dot_com_dot_bapis_dot_bilibili_dot_app_dot_card_dot_v1_dot_LargeCoverV1__pb2
from pyproto.com.bapis.bilibili.app.card.v1 import MiddleCoverV3_pb2 as pyproto_dot_com_dot_bapis_dot_bilibili_dot_app_dot_card_dot_v1_dot_MiddleCoverV3__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pyproto/com.bapis.bilibili.app.card.v1.Card.proto',
  package='com.bapis.bilibili.app.card.v1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n1pyproto/com.bapis.bilibili.app.card.v1.Card.proto\x12\x1e\x63om.bapis.bilibili.app.card.v1\x1a;pyproto/com.bapis.bilibili.app.card.v1.ThreeItemAllV2.proto\x1a\x39pyproto/com.bapis.bilibili.app.card.v1.LargeCoverV4.proto\x1a?pyproto/com.bapis.bilibili.app.card.v1.PopularTopEntrance.proto\x1a\x37pyproto/com.bapis.bilibili.app.card.v1.DynamicHot.proto\x1a\x39pyproto/com.bapis.bilibili.app.card.v1.SmallCoverV5.proto\x1a\x38pyproto/com.bapis.bilibili.app.card.v1.ThreeItemV1.proto\x1a\x35pyproto/com.bapis.bilibili.app.card.v1.HotTopic.proto\x1a\x38pyproto/com.bapis.bilibili.app.card.v1.RcmdOneItem.proto\x1a\x39pyproto/com.bapis.bilibili.app.card.v1.LargeCoverV1.proto\x1a:pyproto/com.bapis.bilibili.app.card.v1.MiddleCoverV3.proto\"\xe3\x05\n\x04\x43\x61rd\x12=\n\thot_topic\x18\x05 \x01(\x0b\x32(.com.bapis.bilibili.app.card.v1.HotTopicH\x00\x12\x46\n\x0elarge_cover_v1\x18\x02 \x01(\x0b\x32,.com.bapis.bilibili.app.card.v1.LargeCoverV1H\x00\x12\x46\n\x0elarge_cover_v4\x18\x08 \x01(\x0b\x32,.com.bapis.bilibili.app.card.v1.LargeCoverV4H\x00\x12H\n\x0fmiddle_cover_v3\x18\x07 \x01(\x0b\x32-.com.bapis.bilibili.app.card.v1.MiddleCoverV3H\x00\x12R\n\x14popular_top_entrance\x18\t \x01(\x0b\x32\x32.com.bapis.bilibili.app.card.v1.PopularTopEntranceH\x00\x12\x44\n\rrcmd_one_item\x18\n \x01(\x0b\x32+.com.bapis.bilibili.app.card.v1.RcmdOneItemH\x00\x12\x46\n\x0esmall_cover_v5\x18\x01 \x01(\x0b\x32,.com.bapis.bilibili.app.card.v1.SmallCoverV5H\x00\x12K\n\x11three_item_all_v2\x18\x03 \x01(\x0b\x32..com.bapis.bilibili.app.card.v1.ThreeItemAllV2H\x00\x12\x45\n\x0fthree_item_h_v5\x18\x06 \x01(\x0b\x32*.com.bapis.bilibili.app.card.v1.DynamicHotH\x00\x12\x44\n\rthree_item_v1\x18\x04 \x01(\x0b\x32+.com.bapis.bilibili.app.card.v1.ThreeItemV1H\x00\x42\x06\n\x04itemb\x06proto3'
  ,
  dependencies=[pyproto_dot_com_dot_bapis_dot_bilibili_dot_app_dot_card_dot_v1_dot_ThreeItemAllV2__pb2.DESCRIPTOR,pyproto_dot_com_dot_bapis_dot_bilibili_dot_app_dot_card_dot_v1_dot_LargeCoverV4__pb2.DESCRIPTOR,pyproto_dot_com_dot_bapis_dot_bilibili_dot_app_dot_card_dot_v1_dot_PopularTopEntrance__pb2.DESCRIPTOR,pyproto_dot_com_dot_bapis_dot_bilibili_dot_app_dot_card_dot_v1_dot_DynamicHot__pb2.DESCRIPTOR,pyproto_dot_com_dot_bapis_dot_bilibili_dot_app_dot_card_dot_v1_dot_SmallCoverV5__pb2.DESCRIPTOR,pyproto_dot_com_dot_bapis_dot_bilibili_dot_app_dot_card_dot_v1_dot_ThreeItemV1__pb2.DESCRIPTOR,pyproto_dot_com_dot_bapis_dot_bilibili_dot_app_dot_card_dot_v1_dot_HotTopic__pb2.DESCRIPTOR,pyproto_dot_com_dot_bapis_dot_bilibili_dot_app_dot_card_dot_v1_dot_RcmdOneItem__pb2.DESCRIPTOR,pyproto_dot_com_dot_bapis_dot_bilibili_dot_app_dot_card_dot_v1_dot_LargeCoverV1__pb2.DESCRIPTOR,pyproto_dot_com_dot_bapis_dot_bilibili_dot_app_dot_card_dot_v1_dot_MiddleCoverV3__pb2.DESCRIPTOR,])




_CARD = _descriptor.Descriptor(
  name='Card',
  full_name='com.bapis.bilibili.app.card.v1.Card',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='hot_topic', full_name='com.bapis.bilibili.app.card.v1.Card.hot_topic', index=0,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='large_cover_v1', full_name='com.bapis.bilibili.app.card.v1.Card.large_cover_v1', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='large_cover_v4', full_name='com.bapis.bilibili.app.card.v1.Card.large_cover_v4', index=2,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='middle_cover_v3', full_name='com.bapis.bilibili.app.card.v1.Card.middle_cover_v3', index=3,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='popular_top_entrance', full_name='com.bapis.bilibili.app.card.v1.Card.popular_top_entrance', index=4,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rcmd_one_item', full_name='com.bapis.bilibili.app.card.v1.Card.rcmd_one_item', index=5,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='small_cover_v5', full_name='com.bapis.bilibili.app.card.v1.Card.small_cover_v5', index=6,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='three_item_all_v2', full_name='com.bapis.bilibili.app.card.v1.Card.three_item_all_v2', index=7,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='three_item_h_v5', full_name='com.bapis.bilibili.app.card.v1.Card.three_item_h_v5', index=8,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='three_item_v1', full_name='com.bapis.bilibili.app.card.v1.Card.three_item_v1', index=9,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='item', full_name='com.bapis.bilibili.app.card.v1.Card.item',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=677,
  serialized_end=1416,
)

_CARD.fields_by_name['hot_topic'].message_type = pyproto_dot_com_dot_bapis_dot_bilibili_dot_app_dot_card_dot_v1_dot_HotTopic__pb2._HOTTOPIC
_CARD.fields_by_name['large_cover_v1'].message_type = pyproto_dot_com_dot_bapis_dot_bilibili_dot_app_dot_card_dot_v1_dot_LargeCoverV1__pb2._LARGECOVERV1
_CARD.fields_by_name['large_cover_v4'].message_type = pyproto_dot_com_dot_bapis_dot_bilibili_dot_app_dot_card_dot_v1_dot_LargeCoverV4__pb2._LARGECOVERV4
_CARD.fields_by_name['middle_cover_v3'].message_type = pyproto_dot_com_dot_bapis_dot_bilibili_dot_app_dot_card_dot_v1_dot_MiddleCoverV3__pb2._MIDDLECOVERV3
_CARD.fields_by_name['popular_top_entrance'].message_type = pyproto_dot_com_dot_bapis_dot_bilibili_dot_app_dot_card_dot_v1_dot_PopularTopEntrance__pb2._POPULARTOPENTRANCE
_CARD.fields_by_name['rcmd_one_item'].message_type = pyproto_dot_com_dot_bapis_dot_bilibili_dot_app_dot_card_dot_v1_dot_RcmdOneItem__pb2._RCMDONEITEM
_CARD.fields_by_name['small_cover_v5'].message_type = pyproto_dot_com_dot_bapis_dot_bilibili_dot_app_dot_card_dot_v1_dot_SmallCoverV5__pb2._SMALLCOVERV5
_CARD.fields_by_name['three_item_all_v2'].message_type = pyproto_dot_com_dot_bapis_dot_bilibili_dot_app_dot_card_dot_v1_dot_ThreeItemAllV2__pb2._THREEITEMALLV2
_CARD.fields_by_name['three_item_h_v5'].message_type = pyproto_dot_com_dot_bapis_dot_bilibili_dot_app_dot_card_dot_v1_dot_DynamicHot__pb2._DYNAMICHOT
_CARD.fields_by_name['three_item_v1'].message_type = pyproto_dot_com_dot_bapis_dot_bilibili_dot_app_dot_card_dot_v1_dot_ThreeItemV1__pb2._THREEITEMV1
_CARD.oneofs_by_name['item'].fields.append(
  _CARD.fields_by_name['hot_topic'])
_CARD.fields_by_name['hot_topic'].containing_oneof = _CARD.oneofs_by_name['item']
_CARD.oneofs_by_name['item'].fields.append(
  _CARD.fields_by_name['large_cover_v1'])
_CARD.fields_by_name['large_cover_v1'].containing_oneof = _CARD.oneofs_by_name['item']
_CARD.oneofs_by_name['item'].fields.append(
  _CARD.fields_by_name['large_cover_v4'])
_CARD.fields_by_name['large_cover_v4'].containing_oneof = _CARD.oneofs_by_name['item']
_CARD.oneofs_by_name['item'].fields.append(
  _CARD.fields_by_name['middle_cover_v3'])
_CARD.fields_by_name['middle_cover_v3'].containing_oneof = _CARD.oneofs_by_name['item']
_CARD.oneofs_by_name['item'].fields.append(
  _CARD.fields_by_name['popular_top_entrance'])
_CARD.fields_by_name['popular_top_entrance'].containing_oneof = _CARD.oneofs_by_name['item']
_CARD.oneofs_by_name['item'].fields.append(
  _CARD.fields_by_name['rcmd_one_item'])
_CARD.fields_by_name['rcmd_one_item'].containing_oneof = _CARD.oneofs_by_name['item']
_CARD.oneofs_by_name['item'].fields.append(
  _CARD.fields_by_name['small_cover_v5'])
_CARD.fields_by_name['small_cover_v5'].containing_oneof = _CARD.oneofs_by_name['item']
_CARD.oneofs_by_name['item'].fields.append(
  _CARD.fields_by_name['three_item_all_v2'])
_CARD.fields_by_name['three_item_all_v2'].containing_oneof = _CARD.oneofs_by_name['item']
_CARD.oneofs_by_name['item'].fields.append(
  _CARD.fields_by_name['three_item_h_v5'])
_CARD.fields_by_name['three_item_h_v5'].containing_oneof = _CARD.oneofs_by_name['item']
_CARD.oneofs_by_name['item'].fields.append(
  _CARD.fields_by_name['three_item_v1'])
_CARD.fields_by_name['three_item_v1'].containing_oneof = _CARD.oneofs_by_name['item']
DESCRIPTOR.message_types_by_name['Card'] = _CARD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Card = _reflection.GeneratedProtocolMessageType('Card', (_message.Message,), {
  'DESCRIPTOR' : _CARD,
  '__module__' : 'pyproto.com.bapis.bilibili.app.card.v1.Card_pb2'
  # @@protoc_insertion_point(class_scope:com.bapis.bilibili.app.card.v1.Card)
  })
_sym_db.RegisterMessage(Card)


# @@protoc_insertion_point(module_scope)
