# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pyproto/com.bapis.bilibili.app.card.v1.HotTopicItem.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pyproto/com.bapis.bilibili.app.card.v1.HotTopicItem.proto',
  package='com.bapis.bilibili.app.card.v1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n9pyproto/com.bapis.bilibili.app.card.v1.HotTopicItem.proto\x12\x1e\x63om.bapis.bilibili.app.card.v1\"\x80\x01\n\x0cHotTopicItem\x12\x12\n\x05\x63over\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x10\n\x03uri\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x12\n\x05param\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x11\n\x04name\x18\x04 \x01(\tH\x03\x88\x01\x01\x42\x08\n\x06_coverB\x06\n\x04_uriB\x08\n\x06_paramB\x07\n\x05_nameb\x06proto3'
)




_HOTTOPICITEM = _descriptor.Descriptor(
  name='HotTopicItem',
  full_name='com.bapis.bilibili.app.card.v1.HotTopicItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cover', full_name='com.bapis.bilibili.app.card.v1.HotTopicItem.cover', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='uri', full_name='com.bapis.bilibili.app.card.v1.HotTopicItem.uri', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='param', full_name='com.bapis.bilibili.app.card.v1.HotTopicItem.param', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='com.bapis.bilibili.app.card.v1.HotTopicItem.name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_cover', full_name='com.bapis.bilibili.app.card.v1.HotTopicItem._cover',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_uri', full_name='com.bapis.bilibili.app.card.v1.HotTopicItem._uri',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_param', full_name='com.bapis.bilibili.app.card.v1.HotTopicItem._param',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_name', full_name='com.bapis.bilibili.app.card.v1.HotTopicItem._name',
      index=3, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=94,
  serialized_end=222,
)

_HOTTOPICITEM.oneofs_by_name['_cover'].fields.append(
  _HOTTOPICITEM.fields_by_name['cover'])
_HOTTOPICITEM.fields_by_name['cover'].containing_oneof = _HOTTOPICITEM.oneofs_by_name['_cover']
_HOTTOPICITEM.oneofs_by_name['_uri'].fields.append(
  _HOTTOPICITEM.fields_by_name['uri'])
_HOTTOPICITEM.fields_by_name['uri'].containing_oneof = _HOTTOPICITEM.oneofs_by_name['_uri']
_HOTTOPICITEM.oneofs_by_name['_param'].fields.append(
  _HOTTOPICITEM.fields_by_name['param'])
_HOTTOPICITEM.fields_by_name['param'].containing_oneof = _HOTTOPICITEM.oneofs_by_name['_param']
_HOTTOPICITEM.oneofs_by_name['_name'].fields.append(
  _HOTTOPICITEM.fields_by_name['name'])
_HOTTOPICITEM.fields_by_name['name'].containing_oneof = _HOTTOPICITEM.oneofs_by_name['_name']
DESCRIPTOR.message_types_by_name['HotTopicItem'] = _HOTTOPICITEM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HotTopicItem = _reflection.GeneratedProtocolMessageType('HotTopicItem', (_message.Message,), {
  'DESCRIPTOR' : _HOTTOPICITEM,
  '__module__' : 'pyproto.com.bapis.bilibili.app.card.v1.HotTopicItem_pb2'
  # @@protoc_insertion_point(class_scope:com.bapis.bilibili.app.card.v1.HotTopicItem)
  })
_sym_db.RegisterMessage(HotTopicItem)


# @@protoc_insertion_point(module_scope)
