# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pyproto/com.bapis.bilibili.app.card.v1.HotwordEntrance.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pyproto/com.bapis.bilibili.app.card.v1.HotwordEntrance.proto',
  package='com.bapis.bilibili.app.card.v1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n<pyproto/com.bapis.bilibili.app.card.v1.HotwordEntrance.proto\x12\x1e\x63om.bapis.bilibili.app.card.v1\"y\n\x0fHotwordEntrance\x12\x17\n\nhotword_id\x18\x01 \x01(\x03H\x00\x88\x01\x01\x12\x15\n\x08hot_text\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x11\n\x04icon\x18\x04 \x01(\tH\x02\x88\x01\x01\x42\r\n\x0b_hotword_idB\x0b\n\t_hot_textB\x07\n\x05_iconb\x06proto3'
)




_HOTWORDENTRANCE = _descriptor.Descriptor(
  name='HotwordEntrance',
  full_name='com.bapis.bilibili.app.card.v1.HotwordEntrance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='hotword_id', full_name='com.bapis.bilibili.app.card.v1.HotwordEntrance.hotword_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hot_text', full_name='com.bapis.bilibili.app.card.v1.HotwordEntrance.hot_text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='icon', full_name='com.bapis.bilibili.app.card.v1.HotwordEntrance.icon', index=2,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_hotword_id', full_name='com.bapis.bilibili.app.card.v1.HotwordEntrance._hotword_id',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_hot_text', full_name='com.bapis.bilibili.app.card.v1.HotwordEntrance._hot_text',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_icon', full_name='com.bapis.bilibili.app.card.v1.HotwordEntrance._icon',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=96,
  serialized_end=217,
)

_HOTWORDENTRANCE.oneofs_by_name['_hotword_id'].fields.append(
  _HOTWORDENTRANCE.fields_by_name['hotword_id'])
_HOTWORDENTRANCE.fields_by_name['hotword_id'].containing_oneof = _HOTWORDENTRANCE.oneofs_by_name['_hotword_id']
_HOTWORDENTRANCE.oneofs_by_name['_hot_text'].fields.append(
  _HOTWORDENTRANCE.fields_by_name['hot_text'])
_HOTWORDENTRANCE.fields_by_name['hot_text'].containing_oneof = _HOTWORDENTRANCE.oneofs_by_name['_hot_text']
_HOTWORDENTRANCE.oneofs_by_name['_icon'].fields.append(
  _HOTWORDENTRANCE.fields_by_name['icon'])
_HOTWORDENTRANCE.fields_by_name['icon'].containing_oneof = _HOTWORDENTRANCE.oneofs_by_name['_icon']
DESCRIPTOR.message_types_by_name['HotwordEntrance'] = _HOTWORDENTRANCE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HotwordEntrance = _reflection.GeneratedProtocolMessageType('HotwordEntrance', (_message.Message,), {
  'DESCRIPTOR' : _HOTWORDENTRANCE,
  '__module__' : 'pyproto.com.bapis.bilibili.app.card.v1.HotwordEntrance_pb2'
  # @@protoc_insertion_point(class_scope:com.bapis.bilibili.app.card.v1.HotwordEntrance)
  })
_sym_db.RegisterMessage(HotwordEntrance)


# @@protoc_insertion_point(module_scope)
