# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pyproto/com.bapis.bilibili.app.card.v1.LikeButton.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pyproto/com.bapis.bilibili.app.card.v1.LikeButton.proto',
  package='com.bapis.bilibili.app.card.v1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n7pyproto/com.bapis.bilibili.app.card.v1.LikeButton.proto\x12\x1e\x63om.bapis.bilibili.app.card.v1\"\xae\x01\n\nLikeButton\x12\x10\n\x03\x61id\x18\x01 \x01(\x03H\x00\x88\x01\x01\x12\x12\n\x05\x63ount\x18\x02 \x01(\x05H\x01\x88\x01\x01\x12\x17\n\nshow_count\x18\x03 \x01(\x08H\x02\x88\x01\x01\x12\x12\n\x05\x65vent\x18\x04 \x01(\tH\x03\x88\x01\x01\x12\x15\n\x08selected\x18\x05 \x01(\x05H\x04\x88\x01\x01\x42\x06\n\x04_aidB\x08\n\x06_countB\r\n\x0b_show_countB\x08\n\x06_eventB\x0b\n\t_selectedb\x06proto3'
)




_LIKEBUTTON = _descriptor.Descriptor(
  name='LikeButton',
  full_name='com.bapis.bilibili.app.card.v1.LikeButton',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='aid', full_name='com.bapis.bilibili.app.card.v1.LikeButton.aid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='count', full_name='com.bapis.bilibili.app.card.v1.LikeButton.count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='show_count', full_name='com.bapis.bilibili.app.card.v1.LikeButton.show_count', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='event', full_name='com.bapis.bilibili.app.card.v1.LikeButton.event', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='selected', full_name='com.bapis.bilibili.app.card.v1.LikeButton.selected', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_aid', full_name='com.bapis.bilibili.app.card.v1.LikeButton._aid',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_count', full_name='com.bapis.bilibili.app.card.v1.LikeButton._count',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_show_count', full_name='com.bapis.bilibili.app.card.v1.LikeButton._show_count',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_event', full_name='com.bapis.bilibili.app.card.v1.LikeButton._event',
      index=3, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_selected', full_name='com.bapis.bilibili.app.card.v1.LikeButton._selected',
      index=4, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=92,
  serialized_end=266,
)

_LIKEBUTTON.oneofs_by_name['_aid'].fields.append(
  _LIKEBUTTON.fields_by_name['aid'])
_LIKEBUTTON.fields_by_name['aid'].containing_oneof = _LIKEBUTTON.oneofs_by_name['_aid']
_LIKEBUTTON.oneofs_by_name['_count'].fields.append(
  _LIKEBUTTON.fields_by_name['count'])
_LIKEBUTTON.fields_by_name['count'].containing_oneof = _LIKEBUTTON.oneofs_by_name['_count']
_LIKEBUTTON.oneofs_by_name['_show_count'].fields.append(
  _LIKEBUTTON.fields_by_name['show_count'])
_LIKEBUTTON.fields_by_name['show_count'].containing_oneof = _LIKEBUTTON.oneofs_by_name['_show_count']
_LIKEBUTTON.oneofs_by_name['_event'].fields.append(
  _LIKEBUTTON.fields_by_name['event'])
_LIKEBUTTON.fields_by_name['event'].containing_oneof = _LIKEBUTTON.oneofs_by_name['_event']
_LIKEBUTTON.oneofs_by_name['_selected'].fields.append(
  _LIKEBUTTON.fields_by_name['selected'])
_LIKEBUTTON.fields_by_name['selected'].containing_oneof = _LIKEBUTTON.oneofs_by_name['_selected']
DESCRIPTOR.message_types_by_name['LikeButton'] = _LIKEBUTTON
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LikeButton = _reflection.GeneratedProtocolMessageType('LikeButton', (_message.Message,), {
  'DESCRIPTOR' : _LIKEBUTTON,
  '__module__' : 'pyproto.com.bapis.bilibili.app.card.v1.LikeButton_pb2'
  # @@protoc_insertion_point(class_scope:com.bapis.bilibili.app.card.v1.LikeButton)
  })
_sym_db.RegisterMessage(LikeButton)


# @@protoc_insertion_point(module_scope)
