# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pyproto/com.bapis.bilibili.app.card.v1.Mask.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pyproto.com.bapis.bilibili.app.card.v1 import Button_pb2 as pyproto_dot_com_dot_bapis_dot_bilibili_dot_app_dot_card_dot_v1_dot_Button__pb2
from pyproto.com.bapis.bilibili.app.card.v1 import Avatar_pb2 as pyproto_dot_com_dot_bapis_dot_bilibili_dot_app_dot_card_dot_v1_dot_Avatar__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pyproto/com.bapis.bilibili.app.card.v1.Mask.proto',
  package='com.bapis.bilibili.app.card.v1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n1pyproto/com.bapis.bilibili.app.card.v1.Mask.proto\x12\x1e\x63om.bapis.bilibili.app.card.v1\x1a\x33pyproto/com.bapis.bilibili.app.card.v1.Button.proto\x1a\x33pyproto/com.bapis.bilibili.app.card.v1.Avatar.proto\"\x96\x01\n\x04Mask\x12;\n\x06\x61vatar\x18\x01 \x01(\x0b\x32&.com.bapis.bilibili.app.card.v1.AvatarH\x00\x88\x01\x01\x12;\n\x06\x62utton\x18\x02 \x01(\x0b\x32&.com.bapis.bilibili.app.card.v1.ButtonH\x01\x88\x01\x01\x42\t\n\x07_avatarB\t\n\x07_buttonb\x06proto3'
  ,
  dependencies=[pyproto_dot_com_dot_bapis_dot_bilibili_dot_app_dot_card_dot_v1_dot_Button__pb2.DESCRIPTOR,pyproto_dot_com_dot_bapis_dot_bilibili_dot_app_dot_card_dot_v1_dot_Avatar__pb2.DESCRIPTOR,])




_MASK = _descriptor.Descriptor(
  name='Mask',
  full_name='com.bapis.bilibili.app.card.v1.Mask',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='avatar', full_name='com.bapis.bilibili.app.card.v1.Mask.avatar', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='button', full_name='com.bapis.bilibili.app.card.v1.Mask.button', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_avatar', full_name='com.bapis.bilibili.app.card.v1.Mask._avatar',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_button', full_name='com.bapis.bilibili.app.card.v1.Mask._button',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=192,
  serialized_end=342,
)

_MASK.fields_by_name['avatar'].message_type = pyproto_dot_com_dot_bapis_dot_bilibili_dot_app_dot_card_dot_v1_dot_Avatar__pb2._AVATAR
_MASK.fields_by_name['button'].message_type = pyproto_dot_com_dot_bapis_dot_bilibili_dot_app_dot_card_dot_v1_dot_Button__pb2._BUTTON
_MASK.oneofs_by_name['_avatar'].fields.append(
  _MASK.fields_by_name['avatar'])
_MASK.fields_by_name['avatar'].containing_oneof = _MASK.oneofs_by_name['_avatar']
_MASK.oneofs_by_name['_button'].fields.append(
  _MASK.fields_by_name['button'])
_MASK.fields_by_name['button'].containing_oneof = _MASK.oneofs_by_name['_button']
DESCRIPTOR.message_types_by_name['Mask'] = _MASK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Mask = _reflection.GeneratedProtocolMessageType('Mask', (_message.Message,), {
  'DESCRIPTOR' : _MASK,
  '__module__' : 'pyproto.com.bapis.bilibili.app.card.v1.Mask_pb2'
  # @@protoc_insertion_point(class_scope:com.bapis.bilibili.app.card.v1.Mask)
  })
_sym_db.RegisterMessage(Mask)


# @@protoc_insertion_point(module_scope)
