# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pyproto/com.bapis.bilibili.app.card.v1.PlayerArgs.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pyproto/com.bapis.bilibili.app.card.v1.PlayerArgs.proto',
  package='com.bapis.bilibili.app.card.v1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n7pyproto/com.bapis.bilibili.app.card.v1.PlayerArgs.proto\x12\x1e\x63om.bapis.bilibili.app.card.v1\"\xd4\x02\n\nPlayerArgs\x12\x14\n\x07is_live\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x10\n\x03\x61id\x18\x02 \x01(\x03H\x01\x88\x01\x01\x12\x10\n\x03\x63id\x18\x03 \x01(\x03H\x02\x88\x01\x01\x12\x15\n\x08sub_type\x18\x04 \x01(\x05H\x03\x88\x01\x01\x12\x14\n\x07room_id\x18\x05 \x01(\x03H\x04\x88\x01\x01\x12\x12\n\x05\x65p_id\x18\x07 \x01(\x03H\x05\x88\x01\x01\x12\x17\n\nis_preview\x18\x08 \x01(\x05H\x06\x88\x01\x01\x12\x11\n\x04type\x18\t \x01(\tH\x07\x88\x01\x01\x12\x15\n\x08\x64uration\x18\n \x01(\x03H\x08\x88\x01\x01\x12\x16\n\tseason_id\x18\x0b \x01(\x03H\t\x88\x01\x01\x42\n\n\x08_is_liveB\x06\n\x04_aidB\x06\n\x04_cidB\x0b\n\t_sub_typeB\n\n\x08_room_idB\x08\n\x06_ep_idB\r\n\x0b_is_previewB\x07\n\x05_typeB\x0b\n\t_durationB\x0c\n\n_season_idb\x06proto3'
)




_PLAYERARGS = _descriptor.Descriptor(
  name='PlayerArgs',
  full_name='com.bapis.bilibili.app.card.v1.PlayerArgs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_live', full_name='com.bapis.bilibili.app.card.v1.PlayerArgs.is_live', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='aid', full_name='com.bapis.bilibili.app.card.v1.PlayerArgs.aid', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cid', full_name='com.bapis.bilibili.app.card.v1.PlayerArgs.cid', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sub_type', full_name='com.bapis.bilibili.app.card.v1.PlayerArgs.sub_type', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='room_id', full_name='com.bapis.bilibili.app.card.v1.PlayerArgs.room_id', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ep_id', full_name='com.bapis.bilibili.app.card.v1.PlayerArgs.ep_id', index=5,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_preview', full_name='com.bapis.bilibili.app.card.v1.PlayerArgs.is_preview', index=6,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='com.bapis.bilibili.app.card.v1.PlayerArgs.type', index=7,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='duration', full_name='com.bapis.bilibili.app.card.v1.PlayerArgs.duration', index=8,
      number=10, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='season_id', full_name='com.bapis.bilibili.app.card.v1.PlayerArgs.season_id', index=9,
      number=11, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_is_live', full_name='com.bapis.bilibili.app.card.v1.PlayerArgs._is_live',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_aid', full_name='com.bapis.bilibili.app.card.v1.PlayerArgs._aid',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_cid', full_name='com.bapis.bilibili.app.card.v1.PlayerArgs._cid',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_sub_type', full_name='com.bapis.bilibili.app.card.v1.PlayerArgs._sub_type',
      index=3, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_room_id', full_name='com.bapis.bilibili.app.card.v1.PlayerArgs._room_id',
      index=4, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_ep_id', full_name='com.bapis.bilibili.app.card.v1.PlayerArgs._ep_id',
      index=5, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_is_preview', full_name='com.bapis.bilibili.app.card.v1.PlayerArgs._is_preview',
      index=6, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_type', full_name='com.bapis.bilibili.app.card.v1.PlayerArgs._type',
      index=7, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_duration', full_name='com.bapis.bilibili.app.card.v1.PlayerArgs._duration',
      index=8, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_season_id', full_name='com.bapis.bilibili.app.card.v1.PlayerArgs._season_id',
      index=9, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=92,
  serialized_end=432,
)

_PLAYERARGS.oneofs_by_name['_is_live'].fields.append(
  _PLAYERARGS.fields_by_name['is_live'])
_PLAYERARGS.fields_by_name['is_live'].containing_oneof = _PLAYERARGS.oneofs_by_name['_is_live']
_PLAYERARGS.oneofs_by_name['_aid'].fields.append(
  _PLAYERARGS.fields_by_name['aid'])
_PLAYERARGS.fields_by_name['aid'].containing_oneof = _PLAYERARGS.oneofs_by_name['_aid']
_PLAYERARGS.oneofs_by_name['_cid'].fields.append(
  _PLAYERARGS.fields_by_name['cid'])
_PLAYERARGS.fields_by_name['cid'].containing_oneof = _PLAYERARGS.oneofs_by_name['_cid']
_PLAYERARGS.oneofs_by_name['_sub_type'].fields.append(
  _PLAYERARGS.fields_by_name['sub_type'])
_PLAYERARGS.fields_by_name['sub_type'].containing_oneof = _PLAYERARGS.oneofs_by_name['_sub_type']
_PLAYERARGS.oneofs_by_name['_room_id'].fields.append(
  _PLAYERARGS.fields_by_name['room_id'])
_PLAYERARGS.fields_by_name['room_id'].containing_oneof = _PLAYERARGS.oneofs_by_name['_room_id']
_PLAYERARGS.oneofs_by_name['_ep_id'].fields.append(
  _PLAYERARGS.fields_by_name['ep_id'])
_PLAYERARGS.fields_by_name['ep_id'].containing_oneof = _PLAYERARGS.oneofs_by_name['_ep_id']
_PLAYERARGS.oneofs_by_name['_is_preview'].fields.append(
  _PLAYERARGS.fields_by_name['is_preview'])
_PLAYERARGS.fields_by_name['is_preview'].containing_oneof = _PLAYERARGS.oneofs_by_name['_is_preview']
_PLAYERARGS.oneofs_by_name['_type'].fields.append(
  _PLAYERARGS.fields_by_name['type'])
_PLAYERARGS.fields_by_name['type'].containing_oneof = _PLAYERARGS.oneofs_by_name['_type']
_PLAYERARGS.oneofs_by_name['_duration'].fields.append(
  _PLAYERARGS.fields_by_name['duration'])
_PLAYERARGS.fields_by_name['duration'].containing_oneof = _PLAYERARGS.oneofs_by_name['_duration']
_PLAYERARGS.oneofs_by_name['_season_id'].fields.append(
  _PLAYERARGS.fields_by_name['season_id'])
_PLAYERARGS.fields_by_name['season_id'].containing_oneof = _PLAYERARGS.oneofs_by_name['_season_id']
DESCRIPTOR.message_types_by_name['PlayerArgs'] = _PLAYERARGS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PlayerArgs = _reflection.GeneratedProtocolMessageType('PlayerArgs', (_message.Message,), {
  'DESCRIPTOR' : _PLAYERARGS,
  '__module__' : 'pyproto.com.bapis.bilibili.app.card.v1.PlayerArgs_pb2'
  # @@protoc_insertion_point(class_scope:com.bapis.bilibili.app.card.v1.PlayerArgs)
  })
_sym_db.RegisterMessage(PlayerArgs)


# @@protoc_insertion_point(module_scope)
