# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pyproto/com.bapis.bilibili.app.card.v1.RcmdOneItem.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pyproto.com.bapis.bilibili.app.card.v1 import ReasonStyle_pb2 as pyproto_dot_com_dot_bapis_dot_bilibili_dot_app_dot_card_dot_v1_dot_ReasonStyle__pb2
from pyproto.com.bapis.bilibili.app.card.v1 import Base_pb2 as pyproto_dot_com_dot_bapis_dot_bilibili_dot_app_dot_card_dot_v1_dot_Base__pb2
from pyproto.com.bapis.bilibili.app.card.v1 import SmallCoverRcmdItem_pb2 as pyproto_dot_com_dot_bapis_dot_bilibili_dot_app_dot_card_dot_v1_dot_SmallCoverRcmdItem__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pyproto/com.bapis.bilibili.app.card.v1.RcmdOneItem.proto',
  package='com.bapis.bilibili.app.card.v1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n8pyproto/com.bapis.bilibili.app.card.v1.RcmdOneItem.proto\x12\x1e\x63om.bapis.bilibili.app.card.v1\x1a\x38pyproto/com.bapis.bilibili.app.card.v1.ReasonStyle.proto\x1a\x31pyproto/com.bapis.bilibili.app.card.v1.Base.proto\x1a?pyproto/com.bapis.bilibili.app.card.v1.SmallCoverRcmdItem.proto\"\x8a\x02\n\x0bRcmdOneItem\x12\x37\n\x04\x62\x61se\x18\x01 \x01(\x0b\x32$.com.bapis.bilibili.app.card.v1.BaseH\x00\x88\x01\x01\x12O\n\x15top_rcmd_reason_style\x18\x02 \x01(\x0b\x32+.com.bapis.bilibili.app.card.v1.ReasonStyleH\x01\x88\x01\x01\x12\x45\n\x04item\x18\x03 \x01(\x0b\x32\x32.com.bapis.bilibili.app.card.v1.SmallCoverRcmdItemH\x02\x88\x01\x01\x42\x07\n\x05_baseB\x18\n\x16_top_rcmd_reason_styleB\x07\n\x05_itemb\x06proto3'
  ,
  dependencies=[pyproto_dot_com_dot_bapis_dot_bilibili_dot_app_dot_card_dot_v1_dot_ReasonStyle__pb2.DESCRIPTOR,pyproto_dot_com_dot_bapis_dot_bilibili_dot_app_dot_card_dot_v1_dot_Base__pb2.DESCRIPTOR,pyproto_dot_com_dot_bapis_dot_bilibili_dot_app_dot_card_dot_v1_dot_SmallCoverRcmdItem__pb2.DESCRIPTOR,])




_RCMDONEITEM = _descriptor.Descriptor(
  name='RcmdOneItem',
  full_name='com.bapis.bilibili.app.card.v1.RcmdOneItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='base', full_name='com.bapis.bilibili.app.card.v1.RcmdOneItem.base', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='top_rcmd_reason_style', full_name='com.bapis.bilibili.app.card.v1.RcmdOneItem.top_rcmd_reason_style', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='item', full_name='com.bapis.bilibili.app.card.v1.RcmdOneItem.item', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_base', full_name='com.bapis.bilibili.app.card.v1.RcmdOneItem._base',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_top_rcmd_reason_style', full_name='com.bapis.bilibili.app.card.v1.RcmdOneItem._top_rcmd_reason_style',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_item', full_name='com.bapis.bilibili.app.card.v1.RcmdOneItem._item',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=267,
  serialized_end=533,
)

_RCMDONEITEM.fields_by_name['base'].message_type = pyproto_dot_com_dot_bapis_dot_bilibili_dot_app_dot_card_dot_v1_dot_Base__pb2._BASE
_RCMDONEITEM.fields_by_name['top_rcmd_reason_style'].message_type = pyproto_dot_com_dot_bapis_dot_bilibili_dot_app_dot_card_dot_v1_dot_ReasonStyle__pb2._REASONSTYLE
_RCMDONEITEM.fields_by_name['item'].message_type = pyproto_dot_com_dot_bapis_dot_bilibili_dot_app_dot_card_dot_v1_dot_SmallCoverRcmdItem__pb2._SMALLCOVERRCMDITEM
_RCMDONEITEM.oneofs_by_name['_base'].fields.append(
  _RCMDONEITEM.fields_by_name['base'])
_RCMDONEITEM.fields_by_name['base'].containing_oneof = _RCMDONEITEM.oneofs_by_name['_base']
_RCMDONEITEM.oneofs_by_name['_top_rcmd_reason_style'].fields.append(
  _RCMDONEITEM.fields_by_name['top_rcmd_reason_style'])
_RCMDONEITEM.fields_by_name['top_rcmd_reason_style'].containing_oneof = _RCMDONEITEM.oneofs_by_name['_top_rcmd_reason_style']
_RCMDONEITEM.oneofs_by_name['_item'].fields.append(
  _RCMDONEITEM.fields_by_name['item'])
_RCMDONEITEM.fields_by_name['item'].containing_oneof = _RCMDONEITEM.oneofs_by_name['_item']
DESCRIPTOR.message_types_by_name['RcmdOneItem'] = _RCMDONEITEM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RcmdOneItem = _reflection.GeneratedProtocolMessageType('RcmdOneItem', (_message.Message,), {
  'DESCRIPTOR' : _RCMDONEITEM,
  '__module__' : 'pyproto.com.bapis.bilibili.app.card.v1.RcmdOneItem_pb2'
  # @@protoc_insertion_point(class_scope:com.bapis.bilibili.app.card.v1.RcmdOneItem)
  })
_sym_db.RegisterMessage(RcmdOneItem)


# @@protoc_insertion_point(module_scope)
