# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pyproto/com.bapis.bilibili.app.card.v1.ReasonStyle.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pyproto/com.bapis.bilibili.app.card.v1.ReasonStyle.proto',
  package='com.bapis.bilibili.app.card.v1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n8pyproto/com.bapis.bilibili.app.card.v1.ReasonStyle.proto\x12\x1e\x63om.bapis.bilibili.app.card.v1\"\xf9\x04\n\x0bReasonStyle\x12\x11\n\x04text\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x17\n\ntext_color\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x15\n\x08\x62g_color\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x19\n\x0c\x62order_color\x18\x04 \x01(\tH\x03\x88\x01\x01\x12\x15\n\x08icon_url\x18\x05 \x01(\tH\x04\x88\x01\x01\x12\x1d\n\x10text_color_night\x18\x06 \x01(\tH\x05\x88\x01\x01\x12\x1b\n\x0e\x62g_color_night\x18\x07 \x01(\tH\x06\x88\x01\x01\x12\x1f\n\x12\x62order_color_night\x18\x08 \x01(\tH\x07\x88\x01\x01\x12\x1b\n\x0eicon_night_url\x18\t \x01(\tH\x08\x88\x01\x01\x12\x15\n\x08\x62g_style\x18\n \x01(\x05H\t\x88\x01\x01\x12\x10\n\x03uri\x18\x0b \x01(\tH\n\x88\x01\x01\x12\x18\n\x0bicon_bg_url\x18\x0c \x01(\tH\x0b\x88\x01\x01\x12\x12\n\x05\x65vent\x18\r \x01(\tH\x0c\x88\x01\x01\x12\x1c\n\x0fright_icon_type\x18\x0f \x01(\x05H\r\x88\x01\x01\x12\x1b\n\x0eleft_icon_type\x18\x10 \x01(\tH\x0e\x88\x01\x01\x42\x07\n\x05_textB\r\n\x0b_text_colorB\x0b\n\t_bg_colorB\x0f\n\r_border_colorB\x0b\n\t_icon_urlB\x13\n\x11_text_color_nightB\x11\n\x0f_bg_color_nightB\x15\n\x13_border_color_nightB\x11\n\x0f_icon_night_urlB\x0b\n\t_bg_styleB\x06\n\x04_uriB\x0e\n\x0c_icon_bg_urlB\x08\n\x06_eventB\x12\n\x10_right_icon_typeB\x11\n\x0f_left_icon_typeb\x06proto3'
)




_REASONSTYLE = _descriptor.Descriptor(
  name='ReasonStyle',
  full_name='com.bapis.bilibili.app.card.v1.ReasonStyle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='com.bapis.bilibili.app.card.v1.ReasonStyle.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='text_color', full_name='com.bapis.bilibili.app.card.v1.ReasonStyle.text_color', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bg_color', full_name='com.bapis.bilibili.app.card.v1.ReasonStyle.bg_color', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='border_color', full_name='com.bapis.bilibili.app.card.v1.ReasonStyle.border_color', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='icon_url', full_name='com.bapis.bilibili.app.card.v1.ReasonStyle.icon_url', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='text_color_night', full_name='com.bapis.bilibili.app.card.v1.ReasonStyle.text_color_night', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bg_color_night', full_name='com.bapis.bilibili.app.card.v1.ReasonStyle.bg_color_night', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='border_color_night', full_name='com.bapis.bilibili.app.card.v1.ReasonStyle.border_color_night', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='icon_night_url', full_name='com.bapis.bilibili.app.card.v1.ReasonStyle.icon_night_url', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bg_style', full_name='com.bapis.bilibili.app.card.v1.ReasonStyle.bg_style', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='uri', full_name='com.bapis.bilibili.app.card.v1.ReasonStyle.uri', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='icon_bg_url', full_name='com.bapis.bilibili.app.card.v1.ReasonStyle.icon_bg_url', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='event', full_name='com.bapis.bilibili.app.card.v1.ReasonStyle.event', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='right_icon_type', full_name='com.bapis.bilibili.app.card.v1.ReasonStyle.right_icon_type', index=13,
      number=15, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='left_icon_type', full_name='com.bapis.bilibili.app.card.v1.ReasonStyle.left_icon_type', index=14,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_text', full_name='com.bapis.bilibili.app.card.v1.ReasonStyle._text',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_text_color', full_name='com.bapis.bilibili.app.card.v1.ReasonStyle._text_color',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_bg_color', full_name='com.bapis.bilibili.app.card.v1.ReasonStyle._bg_color',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_border_color', full_name='com.bapis.bilibili.app.card.v1.ReasonStyle._border_color',
      index=3, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_icon_url', full_name='com.bapis.bilibili.app.card.v1.ReasonStyle._icon_url',
      index=4, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_text_color_night', full_name='com.bapis.bilibili.app.card.v1.ReasonStyle._text_color_night',
      index=5, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_bg_color_night', full_name='com.bapis.bilibili.app.card.v1.ReasonStyle._bg_color_night',
      index=6, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_border_color_night', full_name='com.bapis.bilibili.app.card.v1.ReasonStyle._border_color_night',
      index=7, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_icon_night_url', full_name='com.bapis.bilibili.app.card.v1.ReasonStyle._icon_night_url',
      index=8, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_bg_style', full_name='com.bapis.bilibili.app.card.v1.ReasonStyle._bg_style',
      index=9, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_uri', full_name='com.bapis.bilibili.app.card.v1.ReasonStyle._uri',
      index=10, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_icon_bg_url', full_name='com.bapis.bilibili.app.card.v1.ReasonStyle._icon_bg_url',
      index=11, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_event', full_name='com.bapis.bilibili.app.card.v1.ReasonStyle._event',
      index=12, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_right_icon_type', full_name='com.bapis.bilibili.app.card.v1.ReasonStyle._right_icon_type',
      index=13, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_left_icon_type', full_name='com.bapis.bilibili.app.card.v1.ReasonStyle._left_icon_type',
      index=14, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=93,
  serialized_end=726,
)

_REASONSTYLE.oneofs_by_name['_text'].fields.append(
  _REASONSTYLE.fields_by_name['text'])
_REASONSTYLE.fields_by_name['text'].containing_oneof = _REASONSTYLE.oneofs_by_name['_text']
_REASONSTYLE.oneofs_by_name['_text_color'].fields.append(
  _REASONSTYLE.fields_by_name['text_color'])
_REASONSTYLE.fields_by_name['text_color'].containing_oneof = _REASONSTYLE.oneofs_by_name['_text_color']
_REASONSTYLE.oneofs_by_name['_bg_color'].fields.append(
  _REASONSTYLE.fields_by_name['bg_color'])
_REASONSTYLE.fields_by_name['bg_color'].containing_oneof = _REASONSTYLE.oneofs_by_name['_bg_color']
_REASONSTYLE.oneofs_by_name['_border_color'].fields.append(
  _REASONSTYLE.fields_by_name['border_color'])
_REASONSTYLE.fields_by_name['border_color'].containing_oneof = _REASONSTYLE.oneofs_by_name['_border_color']
_REASONSTYLE.oneofs_by_name['_icon_url'].fields.append(
  _REASONSTYLE.fields_by_name['icon_url'])
_REASONSTYLE.fields_by_name['icon_url'].containing_oneof = _REASONSTYLE.oneofs_by_name['_icon_url']
_REASONSTYLE.oneofs_by_name['_text_color_night'].fields.append(
  _REASONSTYLE.fields_by_name['text_color_night'])
_REASONSTYLE.fields_by_name['text_color_night'].containing_oneof = _REASONSTYLE.oneofs_by_name['_text_color_night']
_REASONSTYLE.oneofs_by_name['_bg_color_night'].fields.append(
  _REASONSTYLE.fields_by_name['bg_color_night'])
_REASONSTYLE.fields_by_name['bg_color_night'].containing_oneof = _REASONSTYLE.oneofs_by_name['_bg_color_night']
_REASONSTYLE.oneofs_by_name['_border_color_night'].fields.append(
  _REASONSTYLE.fields_by_name['border_color_night'])
_REASONSTYLE.fields_by_name['border_color_night'].containing_oneof = _REASONSTYLE.oneofs_by_name['_border_color_night']
_REASONSTYLE.oneofs_by_name['_icon_night_url'].fields.append(
  _REASONSTYLE.fields_by_name['icon_night_url'])
_REASONSTYLE.fields_by_name['icon_night_url'].containing_oneof = _REASONSTYLE.oneofs_by_name['_icon_night_url']
_REASONSTYLE.oneofs_by_name['_bg_style'].fields.append(
  _REASONSTYLE.fields_by_name['bg_style'])
_REASONSTYLE.fields_by_name['bg_style'].containing_oneof = _REASONSTYLE.oneofs_by_name['_bg_style']
_REASONSTYLE.oneofs_by_name['_uri'].fields.append(
  _REASONSTYLE.fields_by_name['uri'])
_REASONSTYLE.fields_by_name['uri'].containing_oneof = _REASONSTYLE.oneofs_by_name['_uri']
_REASONSTYLE.oneofs_by_name['_icon_bg_url'].fields.append(
  _REASONSTYLE.fields_by_name['icon_bg_url'])
_REASONSTYLE.fields_by_name['icon_bg_url'].containing_oneof = _REASONSTYLE.oneofs_by_name['_icon_bg_url']
_REASONSTYLE.oneofs_by_name['_event'].fields.append(
  _REASONSTYLE.fields_by_name['event'])
_REASONSTYLE.fields_by_name['event'].containing_oneof = _REASONSTYLE.oneofs_by_name['_event']
_REASONSTYLE.oneofs_by_name['_right_icon_type'].fields.append(
  _REASONSTYLE.fields_by_name['right_icon_type'])
_REASONSTYLE.fields_by_name['right_icon_type'].containing_oneof = _REASONSTYLE.oneofs_by_name['_right_icon_type']
_REASONSTYLE.oneofs_by_name['_left_icon_type'].fields.append(
  _REASONSTYLE.fields_by_name['left_icon_type'])
_REASONSTYLE.fields_by_name['left_icon_type'].containing_oneof = _REASONSTYLE.oneofs_by_name['_left_icon_type']
DESCRIPTOR.message_types_by_name['ReasonStyle'] = _REASONSTYLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReasonStyle = _reflection.GeneratedProtocolMessageType('ReasonStyle', (_message.Message,), {
  'DESCRIPTOR' : _REASONSTYLE,
  '__module__' : 'pyproto.com.bapis.bilibili.app.card.v1.ReasonStyle_pb2'
  # @@protoc_insertion_point(class_scope:com.bapis.bilibili.app.card.v1.ReasonStyle)
  })
_sym_db.RegisterMessage(ReasonStyle)


# @@protoc_insertion_point(module_scope)
