# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pyproto/com.bapis.bilibili.app.card.v1.Relation.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pyproto/com.bapis.bilibili.app.card.v1.Relation.proto',
  package='com.bapis.bilibili.app.card.v1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n5pyproto/com.bapis.bilibili.app.card.v1.Relation.proto\x12\x1e\x63om.bapis.bilibili.app.card.v1\"z\n\x08Relation\x12\x13\n\x06status\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x16\n\tis_follow\x18\x02 \x01(\x05H\x01\x88\x01\x01\x12\x18\n\x0bis_followed\x18\x03 \x01(\x05H\x02\x88\x01\x01\x42\t\n\x07_statusB\x0c\n\n_is_followB\x0e\n\x0c_is_followedb\x06proto3'
)




_RELATION = _descriptor.Descriptor(
  name='Relation',
  full_name='com.bapis.bilibili.app.card.v1.Relation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='com.bapis.bilibili.app.card.v1.Relation.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_follow', full_name='com.bapis.bilibili.app.card.v1.Relation.is_follow', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_followed', full_name='com.bapis.bilibili.app.card.v1.Relation.is_followed', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_status', full_name='com.bapis.bilibili.app.card.v1.Relation._status',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_is_follow', full_name='com.bapis.bilibili.app.card.v1.Relation._is_follow',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_is_followed', full_name='com.bapis.bilibili.app.card.v1.Relation._is_followed',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=89,
  serialized_end=211,
)

_RELATION.oneofs_by_name['_status'].fields.append(
  _RELATION.fields_by_name['status'])
_RELATION.fields_by_name['status'].containing_oneof = _RELATION.oneofs_by_name['_status']
_RELATION.oneofs_by_name['_is_follow'].fields.append(
  _RELATION.fields_by_name['is_follow'])
_RELATION.fields_by_name['is_follow'].containing_oneof = _RELATION.oneofs_by_name['_is_follow']
_RELATION.oneofs_by_name['_is_followed'].fields.append(
  _RELATION.fields_by_name['is_followed'])
_RELATION.fields_by_name['is_followed'].containing_oneof = _RELATION.oneofs_by_name['_is_followed']
DESCRIPTOR.message_types_by_name['Relation'] = _RELATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Relation = _reflection.GeneratedProtocolMessageType('Relation', (_message.Message,), {
  'DESCRIPTOR' : _RELATION,
  '__module__' : 'pyproto.com.bapis.bilibili.app.card.v1.Relation_pb2'
  # @@protoc_insertion_point(class_scope:com.bapis.bilibili.app.card.v1.Relation)
  })
_sym_db.RegisterMessage(Relation)


# @@protoc_insertion_point(module_scope)
