# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pyproto/com.bapis.bilibili.app.card.v1.SmallCoverRcmdItem.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pyproto/com.bapis.bilibili.app.card.v1.SmallCoverRcmdItem.proto',
  package='com.bapis.bilibili.app.card.v1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n?pyproto/com.bapis.bilibili.app.card.v1.SmallCoverRcmdItem.proto\x12\x1e\x63om.bapis.bilibili.app.card.v1\"\xb2\x03\n\x12SmallCoverRcmdItem\x12\x12\n\x05title\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x12\n\x05\x63over\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x10\n\x03uri\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x12\n\x05param\x18\x04 \x01(\tH\x03\x88\x01\x01\x12\x11\n\x04goto\x18\x05 \x01(\tH\x04\x88\x01\x01\x12\x1f\n\x12\x63over_right_text_1\x18\x06 \x01(\tH\x05\x88\x01\x01\x12\x19\n\x0cright_desc_1\x18\x07 \x01(\tH\x06\x88\x01\x01\x12\x19\n\x0cright_desc_2\x18\x08 \x01(\tH\x07\x88\x01\x01\x12\x16\n\tcover_gif\x18\t \x01(\tH\x08\x88\x01\x01\x12\x19\n\x0cright_icon_1\x18\n \x01(\x05H\t\x88\x01\x01\x12\x19\n\x0cright_icon_2\x18\x0b \x01(\x05H\n\x88\x01\x01\x42\x08\n\x06_titleB\x08\n\x06_coverB\x06\n\x04_uriB\x08\n\x06_paramB\x07\n\x05_gotoB\x15\n\x13_cover_right_text_1B\x0f\n\r_right_desc_1B\x0f\n\r_right_desc_2B\x0c\n\n_cover_gifB\x0f\n\r_right_icon_1B\x0f\n\r_right_icon_2b\x06proto3'
)




_SMALLCOVERRCMDITEM = _descriptor.Descriptor(
  name='SmallCoverRcmdItem',
  full_name='com.bapis.bilibili.app.card.v1.SmallCoverRcmdItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='com.bapis.bilibili.app.card.v1.SmallCoverRcmdItem.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cover', full_name='com.bapis.bilibili.app.card.v1.SmallCoverRcmdItem.cover', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='uri', full_name='com.bapis.bilibili.app.card.v1.SmallCoverRcmdItem.uri', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='param', full_name='com.bapis.bilibili.app.card.v1.SmallCoverRcmdItem.param', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='goto', full_name='com.bapis.bilibili.app.card.v1.SmallCoverRcmdItem.goto', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cover_right_text_1', full_name='com.bapis.bilibili.app.card.v1.SmallCoverRcmdItem.cover_right_text_1', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='right_desc_1', full_name='com.bapis.bilibili.app.card.v1.SmallCoverRcmdItem.right_desc_1', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='right_desc_2', full_name='com.bapis.bilibili.app.card.v1.SmallCoverRcmdItem.right_desc_2', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cover_gif', full_name='com.bapis.bilibili.app.card.v1.SmallCoverRcmdItem.cover_gif', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='right_icon_1', full_name='com.bapis.bilibili.app.card.v1.SmallCoverRcmdItem.right_icon_1', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='right_icon_2', full_name='com.bapis.bilibili.app.card.v1.SmallCoverRcmdItem.right_icon_2', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_title', full_name='com.bapis.bilibili.app.card.v1.SmallCoverRcmdItem._title',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_cover', full_name='com.bapis.bilibili.app.card.v1.SmallCoverRcmdItem._cover',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_uri', full_name='com.bapis.bilibili.app.card.v1.SmallCoverRcmdItem._uri',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_param', full_name='com.bapis.bilibili.app.card.v1.SmallCoverRcmdItem._param',
      index=3, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_goto', full_name='com.bapis.bilibili.app.card.v1.SmallCoverRcmdItem._goto',
      index=4, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_cover_right_text_1', full_name='com.bapis.bilibili.app.card.v1.SmallCoverRcmdItem._cover_right_text_1',
      index=5, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_right_desc_1', full_name='com.bapis.bilibili.app.card.v1.SmallCoverRcmdItem._right_desc_1',
      index=6, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_right_desc_2', full_name='com.bapis.bilibili.app.card.v1.SmallCoverRcmdItem._right_desc_2',
      index=7, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_cover_gif', full_name='com.bapis.bilibili.app.card.v1.SmallCoverRcmdItem._cover_gif',
      index=8, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_right_icon_1', full_name='com.bapis.bilibili.app.card.v1.SmallCoverRcmdItem._right_icon_1',
      index=9, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_right_icon_2', full_name='com.bapis.bilibili.app.card.v1.SmallCoverRcmdItem._right_icon_2',
      index=10, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=100,
  serialized_end=534,
)

_SMALLCOVERRCMDITEM.oneofs_by_name['_title'].fields.append(
  _SMALLCOVERRCMDITEM.fields_by_name['title'])
_SMALLCOVERRCMDITEM.fields_by_name['title'].containing_oneof = _SMALLCOVERRCMDITEM.oneofs_by_name['_title']
_SMALLCOVERRCMDITEM.oneofs_by_name['_cover'].fields.append(
  _SMALLCOVERRCMDITEM.fields_by_name['cover'])
_SMALLCOVERRCMDITEM.fields_by_name['cover'].containing_oneof = _SMALLCOVERRCMDITEM.oneofs_by_name['_cover']
_SMALLCOVERRCMDITEM.oneofs_by_name['_uri'].fields.append(
  _SMALLCOVERRCMDITEM.fields_by_name['uri'])
_SMALLCOVERRCMDITEM.fields_by_name['uri'].containing_oneof = _SMALLCOVERRCMDITEM.oneofs_by_name['_uri']
_SMALLCOVERRCMDITEM.oneofs_by_name['_param'].fields.append(
  _SMALLCOVERRCMDITEM.fields_by_name['param'])
_SMALLCOVERRCMDITEM.fields_by_name['param'].containing_oneof = _SMALLCOVERRCMDITEM.oneofs_by_name['_param']
_SMALLCOVERRCMDITEM.oneofs_by_name['_goto'].fields.append(
  _SMALLCOVERRCMDITEM.fields_by_name['goto'])
_SMALLCOVERRCMDITEM.fields_by_name['goto'].containing_oneof = _SMALLCOVERRCMDITEM.oneofs_by_name['_goto']
_SMALLCOVERRCMDITEM.oneofs_by_name['_cover_right_text_1'].fields.append(
  _SMALLCOVERRCMDITEM.fields_by_name['cover_right_text_1'])
_SMALLCOVERRCMDITEM.fields_by_name['cover_right_text_1'].containing_oneof = _SMALLCOVERRCMDITEM.oneofs_by_name['_cover_right_text_1']
_SMALLCOVERRCMDITEM.oneofs_by_name['_right_desc_1'].fields.append(
  _SMALLCOVERRCMDITEM.fields_by_name['right_desc_1'])
_SMALLCOVERRCMDITEM.fields_by_name['right_desc_1'].containing_oneof = _SMALLCOVERRCMDITEM.oneofs_by_name['_right_desc_1']
_SMALLCOVERRCMDITEM.oneofs_by_name['_right_desc_2'].fields.append(
  _SMALLCOVERRCMDITEM.fields_by_name['right_desc_2'])
_SMALLCOVERRCMDITEM.fields_by_name['right_desc_2'].containing_oneof = _SMALLCOVERRCMDITEM.oneofs_by_name['_right_desc_2']
_SMALLCOVERRCMDITEM.oneofs_by_name['_cover_gif'].fields.append(
  _SMALLCOVERRCMDITEM.fields_by_name['cover_gif'])
_SMALLCOVERRCMDITEM.fields_by_name['cover_gif'].containing_oneof = _SMALLCOVERRCMDITEM.oneofs_by_name['_cover_gif']
_SMALLCOVERRCMDITEM.oneofs_by_name['_right_icon_1'].fields.append(
  _SMALLCOVERRCMDITEM.fields_by_name['right_icon_1'])
_SMALLCOVERRCMDITEM.fields_by_name['right_icon_1'].containing_oneof = _SMALLCOVERRCMDITEM.oneofs_by_name['_right_icon_1']
_SMALLCOVERRCMDITEM.oneofs_by_name['_right_icon_2'].fields.append(
  _SMALLCOVERRCMDITEM.fields_by_name['right_icon_2'])
_SMALLCOVERRCMDITEM.fields_by_name['right_icon_2'].containing_oneof = _SMALLCOVERRCMDITEM.oneofs_by_name['_right_icon_2']
DESCRIPTOR.message_types_by_name['SmallCoverRcmdItem'] = _SMALLCOVERRCMDITEM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SmallCoverRcmdItem = _reflection.GeneratedProtocolMessageType('SmallCoverRcmdItem', (_message.Message,), {
  'DESCRIPTOR' : _SMALLCOVERRCMDITEM,
  '__module__' : 'pyproto.com.bapis.bilibili.app.card.v1.SmallCoverRcmdItem_pb2'
  # @@protoc_insertion_point(class_scope:com.bapis.bilibili.app.card.v1.SmallCoverRcmdItem)
  })
_sym_db.RegisterMessage(SmallCoverRcmdItem)


# @@protoc_insertion_point(module_scope)
