# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pyproto/com.bapis.bilibili.app.card.v1.ThreeItemV1.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pyproto.com.bapis.bilibili.app.card.v1 import Base_pb2 as pyproto_dot_com_dot_bapis_dot_bilibili_dot_app_dot_card_dot_v1_dot_Base__pb2
from pyproto.com.bapis.bilibili.app.card.v1 import ThreeItemV1Item_pb2 as pyproto_dot_com_dot_bapis_dot_bilibili_dot_app_dot_card_dot_v1_dot_ThreeItemV1Item__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pyproto/com.bapis.bilibili.app.card.v1.ThreeItemV1.proto',
  package='com.bapis.bilibili.app.card.v1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n8pyproto/com.bapis.bilibili.app.card.v1.ThreeItemV1.proto\x12\x1e\x63om.bapis.bilibili.app.card.v1\x1a\x31pyproto/com.bapis.bilibili.app.card.v1.Base.proto\x1a<pyproto/com.bapis.bilibili.app.card.v1.ThreeItemV1Item.proto\"\x81\x02\n\x0bThreeItemV1\x12\x37\n\x04\x62\x61se\x18\x01 \x01(\x0b\x32$.com.bapis.bilibili.app.card.v1.BaseH\x00\x88\x01\x01\x12\x17\n\ntitle_icon\x18\x02 \x01(\x05H\x01\x88\x01\x01\x12\x15\n\x08more_uri\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x16\n\tmore_text\x18\x04 \x01(\tH\x03\x88\x01\x01\x12>\n\x05items\x18\x05 \x03(\x0b\x32/.com.bapis.bilibili.app.card.v1.ThreeItemV1ItemB\x07\n\x05_baseB\r\n\x0b_title_iconB\x0b\n\t_more_uriB\x0c\n\n_more_textb\x06proto3'
  ,
  dependencies=[pyproto_dot_com_dot_bapis_dot_bilibili_dot_app_dot_card_dot_v1_dot_Base__pb2.DESCRIPTOR,pyproto_dot_com_dot_bapis_dot_bilibili_dot_app_dot_card_dot_v1_dot_ThreeItemV1Item__pb2.DESCRIPTOR,])




_THREEITEMV1 = _descriptor.Descriptor(
  name='ThreeItemV1',
  full_name='com.bapis.bilibili.app.card.v1.ThreeItemV1',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='base', full_name='com.bapis.bilibili.app.card.v1.ThreeItemV1.base', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='title_icon', full_name='com.bapis.bilibili.app.card.v1.ThreeItemV1.title_icon', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='more_uri', full_name='com.bapis.bilibili.app.card.v1.ThreeItemV1.more_uri', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='more_text', full_name='com.bapis.bilibili.app.card.v1.ThreeItemV1.more_text', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='items', full_name='com.bapis.bilibili.app.card.v1.ThreeItemV1.items', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_base', full_name='com.bapis.bilibili.app.card.v1.ThreeItemV1._base',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_title_icon', full_name='com.bapis.bilibili.app.card.v1.ThreeItemV1._title_icon',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_more_uri', full_name='com.bapis.bilibili.app.card.v1.ThreeItemV1._more_uri',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_more_text', full_name='com.bapis.bilibili.app.card.v1.ThreeItemV1._more_text',
      index=3, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=206,
  serialized_end=463,
)

_THREEITEMV1.fields_by_name['base'].message_type = pyproto_dot_com_dot_bapis_dot_bilibili_dot_app_dot_card_dot_v1_dot_Base__pb2._BASE
_THREEITEMV1.fields_by_name['items'].message_type = pyproto_dot_com_dot_bapis_dot_bilibili_dot_app_dot_card_dot_v1_dot_ThreeItemV1Item__pb2._THREEITEMV1ITEM
_THREEITEMV1.oneofs_by_name['_base'].fields.append(
  _THREEITEMV1.fields_by_name['base'])
_THREEITEMV1.fields_by_name['base'].containing_oneof = _THREEITEMV1.oneofs_by_name['_base']
_THREEITEMV1.oneofs_by_name['_title_icon'].fields.append(
  _THREEITEMV1.fields_by_name['title_icon'])
_THREEITEMV1.fields_by_name['title_icon'].containing_oneof = _THREEITEMV1.oneofs_by_name['_title_icon']
_THREEITEMV1.oneofs_by_name['_more_uri'].fields.append(
  _THREEITEMV1.fields_by_name['more_uri'])
_THREEITEMV1.fields_by_name['more_uri'].containing_oneof = _THREEITEMV1.oneofs_by_name['_more_uri']
_THREEITEMV1.oneofs_by_name['_more_text'].fields.append(
  _THREEITEMV1.fields_by_name['more_text'])
_THREEITEMV1.fields_by_name['more_text'].containing_oneof = _THREEITEMV1.oneofs_by_name['_more_text']
DESCRIPTOR.message_types_by_name['ThreeItemV1'] = _THREEITEMV1
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ThreeItemV1 = _reflection.GeneratedProtocolMessageType('ThreeItemV1', (_message.Message,), {
  'DESCRIPTOR' : _THREEITEMV1,
  '__module__' : 'pyproto.com.bapis.bilibili.app.card.v1.ThreeItemV1_pb2'
  # @@protoc_insertion_point(class_scope:com.bapis.bilibili.app.card.v1.ThreeItemV1)
  })
_sym_db.RegisterMessage(ThreeItemV1)


# @@protoc_insertion_point(module_scope)
