# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pyproto/com.tencent.qqlive.protocol.pb.Action.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pyproto/com.tencent.qqlive.protocol.pb.Action.proto',
  package='com.tencent.qqlive.protocol.pb',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n3pyproto/com.tencent.qqlive.protocol.pb.Action.proto\x12\x1e\x63om.tencent.qqlive.protocol.pb\"\"\n\x06\x41\x63tion\x12\x10\n\x03url\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x06\n\x04_urlb\x06proto3'
)




_ACTION = _descriptor.Descriptor(
  name='Action',
  full_name='com.tencent.qqlive.protocol.pb.Action',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='com.tencent.qqlive.protocol.pb.Action.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_url', full_name='com.tencent.qqlive.protocol.pb.Action._url',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=87,
  serialized_end=121,
)

_ACTION.oneofs_by_name['_url'].fields.append(
  _ACTION.fields_by_name['url'])
_ACTION.fields_by_name['url'].containing_oneof = _ACTION.oneofs_by_name['_url']
DESCRIPTOR.message_types_by_name['Action'] = _ACTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Action = _reflection.GeneratedProtocolMessageType('Action', (_message.Message,), {
  'DESCRIPTOR' : _ACTION,
  '__module__' : 'pyproto.com.tencent.qqlive.protocol.pb.Action_pb2'
  # @@protoc_insertion_point(class_scope:com.tencent.qqlive.protocol.pb.Action)
  })
_sym_db.RegisterMessage(Action)


# @@protoc_insertion_point(module_scope)
