# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pyproto/com.tencent.qqlive.protocol.pb.Attent.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pyproto.com.tencent.qqlive.protocol.pb import AttentUIInfo_pb2 as pyproto_dot_com_dot_tencent_dot_qqlive_dot_protocol_dot_pb_dot_AttentUIInfo__pb2
from pyproto.com.tencent.qqlive.protocol.pb import AttentFakeDisplayInfo_pb2 as pyproto_dot_com_dot_tencent_dot_qqlive_dot_protocol_dot_pb_dot_AttentFakeDisplayInfo__pb2
from pyproto.com.tencent.qqlive.protocol.pb import CalendarItem_pb2 as pyproto_dot_com_dot_tencent_dot_qqlive_dot_protocol_dot_pb_dot_CalendarItem__pb2
from pyproto.com.tencent.qqlive.protocol.pb import AttentTimeConfigType_pb2 as pyproto_dot_com_dot_tencent_dot_qqlive_dot_protocol_dot_pb_dot_AttentTimeConfigType__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pyproto/com.tencent.qqlive.protocol.pb.Attent.proto',
  package='com.tencent.qqlive.protocol.pb',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n3pyproto/com.tencent.qqlive.protocol.pb.Attent.proto\x12\x1e\x63om.tencent.qqlive.protocol.pb\x1a\x39pyproto/com.tencent.qqlive.protocol.pb.AttentUIInfo.proto\x1a\x42pyproto/com.tencent.qqlive.protocol.pb.AttentFakeDisplayInfo.proto\x1a\x39pyproto/com.tencent.qqlive.protocol.pb.CalendarItem.proto\x1a\x41pyproto/com.tencent.qqlive.protocol.pb.AttentTimeConfigType.proto\"\xd3\x04\n\x06\x41ttent\x12\x17\n\nattent_key\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x19\n\x0c\x61ttent_state\x18\x02 \x01(\x05H\x01\x88\x01\x01\x12\x18\n\x0bupdate_time\x18\x03 \x01(\x03H\x02\x88\x01\x01\x12K\n\x10\x61ttent_view_info\x18\x04 \x01(\x0b\x32,.com.tencent.qqlive.protocol.pb.AttentUIInfoH\x03\x88\x01\x01\x12U\n\x11\x66\x61ke_display_info\x18\x05 \x01(\x0b\x32\x35.com.tencent.qqlive.protocol.pb.AttentFakeDisplayInfoH\x04\x88\x01\x01\x12\x18\n\x0b\x61ttent_from\x18\x06 \x01(\tH\x05\x88\x01\x01\x12H\n\rcalendar_item\x18\x07 \x01(\x0b\x32,.com.tencent.qqlive.protocol.pb.CalendarItemH\x06\x88\x01\x01\x12Z\n\x17\x61ttent_time_config_type\x18\x08 \x01(\x0e\x32\x34.com.tencent.qqlive.protocol.pb.AttentTimeConfigTypeH\x07\x88\x01\x01\x42\r\n\x0b_attent_keyB\x0f\n\r_attent_stateB\x0e\n\x0c_update_timeB\x13\n\x11_attent_view_infoB\x14\n\x12_fake_display_infoB\x0e\n\x0c_attent_fromB\x10\n\x0e_calendar_itemB\x1a\n\x18_attent_time_config_typeb\x06proto3'
  ,
  dependencies=[pyproto_dot_com_dot_tencent_dot_qqlive_dot_protocol_dot_pb_dot_AttentUIInfo__pb2.DESCRIPTOR,pyproto_dot_com_dot_tencent_dot_qqlive_dot_protocol_dot_pb_dot_AttentFakeDisplayInfo__pb2.DESCRIPTOR,pyproto_dot_com_dot_tencent_dot_qqlive_dot_protocol_dot_pb_dot_CalendarItem__pb2.DESCRIPTOR,pyproto_dot_com_dot_tencent_dot_qqlive_dot_protocol_dot_pb_dot_AttentTimeConfigType__pb2.DESCRIPTOR,])




_ATTENT = _descriptor.Descriptor(
  name='Attent',
  full_name='com.tencent.qqlive.protocol.pb.Attent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='attent_key', full_name='com.tencent.qqlive.protocol.pb.Attent.attent_key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='attent_state', full_name='com.tencent.qqlive.protocol.pb.Attent.attent_state', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='update_time', full_name='com.tencent.qqlive.protocol.pb.Attent.update_time', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='attent_view_info', full_name='com.tencent.qqlive.protocol.pb.Attent.attent_view_info', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fake_display_info', full_name='com.tencent.qqlive.protocol.pb.Attent.fake_display_info', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='attent_from', full_name='com.tencent.qqlive.protocol.pb.Attent.attent_from', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='calendar_item', full_name='com.tencent.qqlive.protocol.pb.Attent.calendar_item', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='attent_time_config_type', full_name='com.tencent.qqlive.protocol.pb.Attent.attent_time_config_type', index=7,
      number=8, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_attent_key', full_name='com.tencent.qqlive.protocol.pb.Attent._attent_key',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_attent_state', full_name='com.tencent.qqlive.protocol.pb.Attent._attent_state',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_update_time', full_name='com.tencent.qqlive.protocol.pb.Attent._update_time',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_attent_view_info', full_name='com.tencent.qqlive.protocol.pb.Attent._attent_view_info',
      index=3, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_fake_display_info', full_name='com.tencent.qqlive.protocol.pb.Attent._fake_display_info',
      index=4, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_attent_from', full_name='com.tencent.qqlive.protocol.pb.Attent._attent_from',
      index=5, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_calendar_item', full_name='com.tencent.qqlive.protocol.pb.Attent._calendar_item',
      index=6, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_attent_time_config_type', full_name='com.tencent.qqlive.protocol.pb.Attent._attent_time_config_type',
      index=7, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=341,
  serialized_end=936,
)

_ATTENT.fields_by_name['attent_view_info'].message_type = pyproto_dot_com_dot_tencent_dot_qqlive_dot_protocol_dot_pb_dot_AttentUIInfo__pb2._ATTENTUIINFO
_ATTENT.fields_by_name['fake_display_info'].message_type = pyproto_dot_com_dot_tencent_dot_qqlive_dot_protocol_dot_pb_dot_AttentFakeDisplayInfo__pb2._ATTENTFAKEDISPLAYINFO
_ATTENT.fields_by_name['calendar_item'].message_type = pyproto_dot_com_dot_tencent_dot_qqlive_dot_protocol_dot_pb_dot_CalendarItem__pb2._CALENDARITEM
_ATTENT.fields_by_name['attent_time_config_type'].enum_type = pyproto_dot_com_dot_tencent_dot_qqlive_dot_protocol_dot_pb_dot_AttentTimeConfigType__pb2._ATTENTTIMECONFIGTYPE
_ATTENT.oneofs_by_name['_attent_key'].fields.append(
  _ATTENT.fields_by_name['attent_key'])
_ATTENT.fields_by_name['attent_key'].containing_oneof = _ATTENT.oneofs_by_name['_attent_key']
_ATTENT.oneofs_by_name['_attent_state'].fields.append(
  _ATTENT.fields_by_name['attent_state'])
_ATTENT.fields_by_name['attent_state'].containing_oneof = _ATTENT.oneofs_by_name['_attent_state']
_ATTENT.oneofs_by_name['_update_time'].fields.append(
  _ATTENT.fields_by_name['update_time'])
_ATTENT.fields_by_name['update_time'].containing_oneof = _ATTENT.oneofs_by_name['_update_time']
_ATTENT.oneofs_by_name['_attent_view_info'].fields.append(
  _ATTENT.fields_by_name['attent_view_info'])
_ATTENT.fields_by_name['attent_view_info'].containing_oneof = _ATTENT.oneofs_by_name['_attent_view_info']
_ATTENT.oneofs_by_name['_fake_display_info'].fields.append(
  _ATTENT.fields_by_name['fake_display_info'])
_ATTENT.fields_by_name['fake_display_info'].containing_oneof = _ATTENT.oneofs_by_name['_fake_display_info']
_ATTENT.oneofs_by_name['_attent_from'].fields.append(
  _ATTENT.fields_by_name['attent_from'])
_ATTENT.fields_by_name['attent_from'].containing_oneof = _ATTENT.oneofs_by_name['_attent_from']
_ATTENT.oneofs_by_name['_calendar_item'].fields.append(
  _ATTENT.fields_by_name['calendar_item'])
_ATTENT.fields_by_name['calendar_item'].containing_oneof = _ATTENT.oneofs_by_name['_calendar_item']
_ATTENT.oneofs_by_name['_attent_time_config_type'].fields.append(
  _ATTENT.fields_by_name['attent_time_config_type'])
_ATTENT.fields_by_name['attent_time_config_type'].containing_oneof = _ATTENT.oneofs_by_name['_attent_time_config_type']
DESCRIPTOR.message_types_by_name['Attent'] = _ATTENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Attent = _reflection.GeneratedProtocolMessageType('Attent', (_message.Message,), {
  'DESCRIPTOR' : _ATTENT,
  '__module__' : 'pyproto.com.tencent.qqlive.protocol.pb.Attent_pb2'
  # @@protoc_insertion_point(class_scope:com.tencent.qqlive.protocol.pb.Attent)
  })
_sym_db.RegisterMessage(Attent)


# @@protoc_insertion_point(module_scope)
