# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pyproto/com.tencent.qqlive.protocol.pb.AttentFakeDisplayInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pyproto.com.tencent.qqlive.protocol.pb import VideoIdSet_pb2 as pyproto_dot_com_dot_tencent_dot_qqlive_dot_protocol_dot_pb_dot_VideoIdSet__pb2
from pyproto.com.tencent.qqlive.protocol.pb import Poster_pb2 as pyproto_dot_com_dot_tencent_dot_qqlive_dot_protocol_dot_pb_dot_Poster__pb2
from pyproto.com.tencent.qqlive.protocol.pb import Operation_pb2 as pyproto_dot_com_dot_tencent_dot_qqlive_dot_protocol_dot_pb_dot_Operation__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pyproto/com.tencent.qqlive.protocol.pb.AttentFakeDisplayInfo.proto',
  package='com.tencent.qqlive.protocol.pb',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nBpyproto/com.tencent.qqlive.protocol.pb.AttentFakeDisplayInfo.proto\x12\x1e\x63om.tencent.qqlive.protocol.pb\x1a\x37pyproto/com.tencent.qqlive.protocol.pb.VideoIdSet.proto\x1a\x33pyproto/com.tencent.qqlive.protocol.pb.Poster.proto\x1a\x36pyproto/com.tencent.qqlive.protocol.pb.Operation.proto\"\x82\x02\n\x15\x41ttentFakeDisplayInfo\x12;\n\x06poster\x18\x01 \x01(\x0b\x32&.com.tencent.qqlive.protocol.pb.PosterH\x00\x88\x01\x01\x12>\n\x06\x61\x63tion\x18\x02 \x01(\x0b\x32).com.tencent.qqlive.protocol.pb.OperationH\x01\x88\x01\x01\x12\x45\n\x0cvideo_id_set\x18\x03 \x01(\x0b\x32*.com.tencent.qqlive.protocol.pb.VideoIdSetH\x02\x88\x01\x01\x42\t\n\x07_posterB\t\n\x07_actionB\x0f\n\r_video_id_setb\x06proto3'
  ,
  dependencies=[pyproto_dot_com_dot_tencent_dot_qqlive_dot_protocol_dot_pb_dot_VideoIdSet__pb2.DESCRIPTOR,pyproto_dot_com_dot_tencent_dot_qqlive_dot_protocol_dot_pb_dot_Poster__pb2.DESCRIPTOR,pyproto_dot_com_dot_tencent_dot_qqlive_dot_protocol_dot_pb_dot_Operation__pb2.DESCRIPTOR,])




_ATTENTFAKEDISPLAYINFO = _descriptor.Descriptor(
  name='AttentFakeDisplayInfo',
  full_name='com.tencent.qqlive.protocol.pb.AttentFakeDisplayInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='poster', full_name='com.tencent.qqlive.protocol.pb.AttentFakeDisplayInfo.poster', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='action', full_name='com.tencent.qqlive.protocol.pb.AttentFakeDisplayInfo.action', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='video_id_set', full_name='com.tencent.qqlive.protocol.pb.AttentFakeDisplayInfo.video_id_set', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_poster', full_name='com.tencent.qqlive.protocol.pb.AttentFakeDisplayInfo._poster',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_action', full_name='com.tencent.qqlive.protocol.pb.AttentFakeDisplayInfo._action',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_video_id_set', full_name='com.tencent.qqlive.protocol.pb.AttentFakeDisplayInfo._video_id_set',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=269,
  serialized_end=527,
)

_ATTENTFAKEDISPLAYINFO.fields_by_name['poster'].message_type = pyproto_dot_com_dot_tencent_dot_qqlive_dot_protocol_dot_pb_dot_Poster__pb2._POSTER
_ATTENTFAKEDISPLAYINFO.fields_by_name['action'].message_type = pyproto_dot_com_dot_tencent_dot_qqlive_dot_protocol_dot_pb_dot_Operation__pb2._OPERATION
_ATTENTFAKEDISPLAYINFO.fields_by_name['video_id_set'].message_type = pyproto_dot_com_dot_tencent_dot_qqlive_dot_protocol_dot_pb_dot_VideoIdSet__pb2._VIDEOIDSET
_ATTENTFAKEDISPLAYINFO.oneofs_by_name['_poster'].fields.append(
  _ATTENTFAKEDISPLAYINFO.fields_by_name['poster'])
_ATTENTFAKEDISPLAYINFO.fields_by_name['poster'].containing_oneof = _ATTENTFAKEDISPLAYINFO.oneofs_by_name['_poster']
_ATTENTFAKEDISPLAYINFO.oneofs_by_name['_action'].fields.append(
  _ATTENTFAKEDISPLAYINFO.fields_by_name['action'])
_ATTENTFAKEDISPLAYINFO.fields_by_name['action'].containing_oneof = _ATTENTFAKEDISPLAYINFO.oneofs_by_name['_action']
_ATTENTFAKEDISPLAYINFO.oneofs_by_name['_video_id_set'].fields.append(
  _ATTENTFAKEDISPLAYINFO.fields_by_name['video_id_set'])
_ATTENTFAKEDISPLAYINFO.fields_by_name['video_id_set'].containing_oneof = _ATTENTFAKEDISPLAYINFO.oneofs_by_name['_video_id_set']
DESCRIPTOR.message_types_by_name['AttentFakeDisplayInfo'] = _ATTENTFAKEDISPLAYINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AttentFakeDisplayInfo = _reflection.GeneratedProtocolMessageType('AttentFakeDisplayInfo', (_message.Message,), {
  'DESCRIPTOR' : _ATTENTFAKEDISPLAYINFO,
  '__module__' : 'pyproto.com.tencent.qqlive.protocol.pb.AttentFakeDisplayInfo_pb2'
  # @@protoc_insertion_point(class_scope:com.tencent.qqlive.protocol.pb.AttentFakeDisplayInfo)
  })
_sym_db.RegisterMessage(AttentFakeDisplayInfo)


# @@protoc_insertion_point(module_scope)
