# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pyproto/com.tencent.qqlive.protocol.pb.CalendarItem.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pyproto/com.tencent.qqlive.protocol.pb.CalendarItem.proto',
  package='com.tencent.qqlive.protocol.pb',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n9pyproto/com.tencent.qqlive.protocol.pb.CalendarItem.proto\x12\x1e\x63om.tencent.qqlive.protocol.pb\"\xa8\x01\n\x0c\x43\x61lendarItem\x12\x17\n\nstart_time\x18\x01 \x01(\x03H\x00\x88\x01\x01\x12\x18\n\x0bis_full_day\x18\x02 \x01(\x08H\x01\x88\x01\x01\x12\x18\n\x0b\x64\x65scription\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x12\n\x05title\x18\x04 \x01(\tH\x03\x88\x01\x01\x42\r\n\x0b_start_timeB\x0e\n\x0c_is_full_dayB\x0e\n\x0c_descriptionB\x08\n\x06_titleb\x06proto3'
)




_CALENDARITEM = _descriptor.Descriptor(
  name='CalendarItem',
  full_name='com.tencent.qqlive.protocol.pb.CalendarItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='start_time', full_name='com.tencent.qqlive.protocol.pb.CalendarItem.start_time', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_full_day', full_name='com.tencent.qqlive.protocol.pb.CalendarItem.is_full_day', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='com.tencent.qqlive.protocol.pb.CalendarItem.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='title', full_name='com.tencent.qqlive.protocol.pb.CalendarItem.title', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_start_time', full_name='com.tencent.qqlive.protocol.pb.CalendarItem._start_time',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_is_full_day', full_name='com.tencent.qqlive.protocol.pb.CalendarItem._is_full_day',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_description', full_name='com.tencent.qqlive.protocol.pb.CalendarItem._description',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_title', full_name='com.tencent.qqlive.protocol.pb.CalendarItem._title',
      index=3, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=94,
  serialized_end=262,
)

_CALENDARITEM.oneofs_by_name['_start_time'].fields.append(
  _CALENDARITEM.fields_by_name['start_time'])
_CALENDARITEM.fields_by_name['start_time'].containing_oneof = _CALENDARITEM.oneofs_by_name['_start_time']
_CALENDARITEM.oneofs_by_name['_is_full_day'].fields.append(
  _CALENDARITEM.fields_by_name['is_full_day'])
_CALENDARITEM.fields_by_name['is_full_day'].containing_oneof = _CALENDARITEM.oneofs_by_name['_is_full_day']
_CALENDARITEM.oneofs_by_name['_description'].fields.append(
  _CALENDARITEM.fields_by_name['description'])
_CALENDARITEM.fields_by_name['description'].containing_oneof = _CALENDARITEM.oneofs_by_name['_description']
_CALENDARITEM.oneofs_by_name['_title'].fields.append(
  _CALENDARITEM.fields_by_name['title'])
_CALENDARITEM.fields_by_name['title'].containing_oneof = _CALENDARITEM.oneofs_by_name['_title']
DESCRIPTOR.message_types_by_name['CalendarItem'] = _CALENDARITEM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CalendarItem = _reflection.GeneratedProtocolMessageType('CalendarItem', (_message.Message,), {
  'DESCRIPTOR' : _CALENDARITEM,
  '__module__' : 'pyproto.com.tencent.qqlive.protocol.pb.CalendarItem_pb2'
  # @@protoc_insertion_point(class_scope:com.tencent.qqlive.protocol.pb.CalendarItem)
  })
_sym_db.RegisterMessage(CalendarItem)


# @@protoc_insertion_point(module_scope)
