# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pyproto/com.tencent.qqlive.protocol.pb.ChangeSectionResponse.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pyproto.com.tencent.qqlive.protocol.pb import Attent_pb2 as pyproto_dot_com_dot_tencent_dot_qqlive_dot_protocol_dot_pb_dot_Attent__pb2
from pyproto.com.tencent.qqlive.protocol.pb import Action_pb2 as pyproto_dot_com_dot_tencent_dot_qqlive_dot_protocol_dot_pb_dot_Action__pb2
from pyproto.com.tencent.qqlive.protocol.pb import VideoIdKeyValueSet_pb2 as pyproto_dot_com_dot_tencent_dot_qqlive_dot_protocol_dot_pb_dot_VideoIdKeyValueSet__pb2
from pyproto.com.tencent.qqlive.protocol.pb import Poster_pb2 as pyproto_dot_com_dot_tencent_dot_qqlive_dot_protocol_dot_pb_dot_Poster__pb2
from pyproto.com.tencent.qqlive.protocol.pb import Section_pb2 as pyproto_dot_com_dot_tencent_dot_qqlive_dot_protocol_dot_pb_dot_Section__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pyproto/com.tencent.qqlive.protocol.pb.ChangeSectionResponse.proto',
  package='com.tencent.qqlive.protocol.pb',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nBpyproto/com.tencent.qqlive.protocol.pb.ChangeSectionResponse.proto\x12\x1e\x63om.tencent.qqlive.protocol.pb\x1a\x33pyproto/com.tencent.qqlive.protocol.pb.Attent.proto\x1a\x33pyproto/com.tencent.qqlive.protocol.pb.Action.proto\x1a?pyproto/com.tencent.qqlive.protocol.pb.VideoIdKeyValueSet.proto\x1a\x33pyproto/com.tencent.qqlive.protocol.pb.Poster.proto\x1a\x34pyproto/com.tencent.qqlive.protocol.pb.Section.proto\"\x9a\x02\n\x15\x43hangeSectionResponse\x12=\n\x07section\x18\x01 \x01(\x0b\x32\'.com.tencent.qqlive.protocol.pb.SectionH\x00\x88\x01\x01\x12Z\n\x0bsection_map\x18\x02 \x03(\x0b\x32\x45.com.tencent.qqlive.protocol.pb.ChangeSectionResponse.SectionMapEntry\x1aZ\n\x0fSectionMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x36\n\x05value\x18\x02 \x01(\x0b\x32\'.com.tencent.qqlive.protocol.pb.Section:\x02\x38\x01\x42\n\n\x08_sectionb\x06proto3'
  ,
  dependencies=[pyproto_dot_com_dot_tencent_dot_qqlive_dot_protocol_dot_pb_dot_Attent__pb2.DESCRIPTOR,pyproto_dot_com_dot_tencent_dot_qqlive_dot_protocol_dot_pb_dot_Action__pb2.DESCRIPTOR,pyproto_dot_com_dot_tencent_dot_qqlive_dot_protocol_dot_pb_dot_VideoIdKeyValueSet__pb2.DESCRIPTOR,pyproto_dot_com_dot_tencent_dot_qqlive_dot_protocol_dot_pb_dot_Poster__pb2.DESCRIPTOR,pyproto_dot_com_dot_tencent_dot_qqlive_dot_protocol_dot_pb_dot_Section__pb2.DESCRIPTOR,])




_CHANGESECTIONRESPONSE_SECTIONMAPENTRY = _descriptor.Descriptor(
  name='SectionMapEntry',
  full_name='com.tencent.qqlive.protocol.pb.ChangeSectionResponse.SectionMapEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='com.tencent.qqlive.protocol.pb.ChangeSectionResponse.SectionMapEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='com.tencent.qqlive.protocol.pb.ChangeSectionResponse.SectionMapEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=561,
  serialized_end=651,
)

_CHANGESECTIONRESPONSE = _descriptor.Descriptor(
  name='ChangeSectionResponse',
  full_name='com.tencent.qqlive.protocol.pb.ChangeSectionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='section', full_name='com.tencent.qqlive.protocol.pb.ChangeSectionResponse.section', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='section_map', full_name='com.tencent.qqlive.protocol.pb.ChangeSectionResponse.section_map', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_CHANGESECTIONRESPONSE_SECTIONMAPENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_section', full_name='com.tencent.qqlive.protocol.pb.ChangeSectionResponse._section',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=381,
  serialized_end=663,
)

_CHANGESECTIONRESPONSE_SECTIONMAPENTRY.fields_by_name['value'].message_type = pyproto_dot_com_dot_tencent_dot_qqlive_dot_protocol_dot_pb_dot_Section__pb2._SECTION
_CHANGESECTIONRESPONSE_SECTIONMAPENTRY.containing_type = _CHANGESECTIONRESPONSE
_CHANGESECTIONRESPONSE.fields_by_name['section'].message_type = pyproto_dot_com_dot_tencent_dot_qqlive_dot_protocol_dot_pb_dot_Section__pb2._SECTION
_CHANGESECTIONRESPONSE.fields_by_name['section_map'].message_type = _CHANGESECTIONRESPONSE_SECTIONMAPENTRY
_CHANGESECTIONRESPONSE.oneofs_by_name['_section'].fields.append(
  _CHANGESECTIONRESPONSE.fields_by_name['section'])
_CHANGESECTIONRESPONSE.fields_by_name['section'].containing_oneof = _CHANGESECTIONRESPONSE.oneofs_by_name['_section']
DESCRIPTOR.message_types_by_name['ChangeSectionResponse'] = _CHANGESECTIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ChangeSectionResponse = _reflection.GeneratedProtocolMessageType('ChangeSectionResponse', (_message.Message,), {

  'SectionMapEntry' : _reflection.GeneratedProtocolMessageType('SectionMapEntry', (_message.Message,), {
    'DESCRIPTOR' : _CHANGESECTIONRESPONSE_SECTIONMAPENTRY,
    '__module__' : 'pyproto.com.tencent.qqlive.protocol.pb.ChangeSectionResponse_pb2'
    # @@protoc_insertion_point(class_scope:com.tencent.qqlive.protocol.pb.ChangeSectionResponse.SectionMapEntry)
    })
  ,
  'DESCRIPTOR' : _CHANGESECTIONRESPONSE,
  '__module__' : 'pyproto.com.tencent.qqlive.protocol.pb.ChangeSectionResponse_pb2'
  # @@protoc_insertion_point(class_scope:com.tencent.qqlive.protocol.pb.ChangeSectionResponse)
  })
_sym_db.RegisterMessage(ChangeSectionResponse)
_sym_db.RegisterMessage(ChangeSectionResponse.SectionMapEntry)


_CHANGESECTIONRESPONSE_SECTIONMAPENTRY._options = None
# @@protoc_insertion_point(module_scope)
