# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pyproto/com.tencent.qqlive.protocol.pb.CSSStruct.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pyproto.com.tencent.qqlive.protocol.pb import CommonStyleMap_pb2 as pyproto_dot_com_dot_tencent_dot_qqlive_dot_protocol_dot_pb_dot_CommonStyleMap__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pyproto/com.tencent.qqlive.protocol.pb.CSSStruct.proto',
  package='com.tencent.qqlive.protocol.pb',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n6pyproto/com.tencent.qqlive.protocol.pb.CSSStruct.proto\x12\x1e\x63om.tencent.qqlive.protocol.pb\x1a;pyproto/com.tencent.qqlive.protocol.pb.CommonStyleMap.proto\"\xe2\x01\n\tCSSStruct\x12\x15\n\x08\x63ss_name\x18\x01 \x01(\tH\x00\x88\x01\x01\x12N\n\x0bstyle_sheet\x18\x03 \x03(\x0b\x32\x39.com.tencent.qqlive.protocol.pb.CSSStruct.StyleSheetEntry\x1a\x61\n\x0fStyleSheetEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12=\n\x05value\x18\x02 \x01(\x0b\x32..com.tencent.qqlive.protocol.pb.CommonStyleMap:\x02\x38\x01\x42\x0b\n\t_css_nameb\x06proto3'
  ,
  dependencies=[pyproto_dot_com_dot_tencent_dot_qqlive_dot_protocol_dot_pb_dot_CommonStyleMap__pb2.DESCRIPTOR,])




_CSSSTRUCT_STYLESHEETENTRY = _descriptor.Descriptor(
  name='StyleSheetEntry',
  full_name='com.tencent.qqlive.protocol.pb.CSSStruct.StyleSheetEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='com.tencent.qqlive.protocol.pb.CSSStruct.StyleSheetEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='com.tencent.qqlive.protocol.pb.CSSStruct.StyleSheetEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=268,
  serialized_end=365,
)

_CSSSTRUCT = _descriptor.Descriptor(
  name='CSSStruct',
  full_name='com.tencent.qqlive.protocol.pb.CSSStruct',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='css_name', full_name='com.tencent.qqlive.protocol.pb.CSSStruct.css_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='style_sheet', full_name='com.tencent.qqlive.protocol.pb.CSSStruct.style_sheet', index=1,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_CSSSTRUCT_STYLESHEETENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_css_name', full_name='com.tencent.qqlive.protocol.pb.CSSStruct._css_name',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=152,
  serialized_end=378,
)

_CSSSTRUCT_STYLESHEETENTRY.fields_by_name['value'].message_type = pyproto_dot_com_dot_tencent_dot_qqlive_dot_protocol_dot_pb_dot_CommonStyleMap__pb2._COMMONSTYLEMAP
_CSSSTRUCT_STYLESHEETENTRY.containing_type = _CSSSTRUCT
_CSSSTRUCT.fields_by_name['style_sheet'].message_type = _CSSSTRUCT_STYLESHEETENTRY
_CSSSTRUCT.oneofs_by_name['_css_name'].fields.append(
  _CSSSTRUCT.fields_by_name['css_name'])
_CSSSTRUCT.fields_by_name['css_name'].containing_oneof = _CSSSTRUCT.oneofs_by_name['_css_name']
DESCRIPTOR.message_types_by_name['CSSStruct'] = _CSSSTRUCT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CSSStruct = _reflection.GeneratedProtocolMessageType('CSSStruct', (_message.Message,), {

  'StyleSheetEntry' : _reflection.GeneratedProtocolMessageType('StyleSheetEntry', (_message.Message,), {
    'DESCRIPTOR' : _CSSSTRUCT_STYLESHEETENTRY,
    '__module__' : 'pyproto.com.tencent.qqlive.protocol.pb.CSSStruct_pb2'
    # @@protoc_insertion_point(class_scope:com.tencent.qqlive.protocol.pb.CSSStruct.StyleSheetEntry)
    })
  ,
  'DESCRIPTOR' : _CSSSTRUCT,
  '__module__' : 'pyproto.com.tencent.qqlive.protocol.pb.CSSStruct_pb2'
  # @@protoc_insertion_point(class_scope:com.tencent.qqlive.protocol.pb.CSSStruct)
  })
_sym_db.RegisterMessage(CSSStruct)
_sym_db.RegisterMessage(CSSStruct.StyleSheetEntry)


_CSSSTRUCT_STYLESHEETENTRY._options = None
# @@protoc_insertion_point(module_scope)
