# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pyproto/com.tencent.qqlive.protocol.pb.Poster.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pyproto.com.tencent.qqlive.protocol.pb import ImageFacePoint_pb2 as pyproto_dot_com_dot_tencent_dot_qqlive_dot_protocol_dot_pb_dot_ImageFacePoint__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pyproto/com.tencent.qqlive.protocol.pb.Poster.proto',
  package='com.tencent.qqlive.protocol.pb',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n3pyproto/com.tencent.qqlive.protocol.pb.Poster.proto\x12\x1e\x63om.tencent.qqlive.protocol.pb\x1a;pyproto/com.tencent.qqlive.protocol.pb.ImageFacePoint.proto\"\xa2\x02\n\x06Poster\x12\x12\n\x05title\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x16\n\tsub_title\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x18\n\x0bthird_title\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x16\n\timage_url\x18\x04 \x01(\tH\x03\x88\x01\x01\x12\x1a\n\rpicture_ratio\x18\x05 \x01(\x02H\x04\x88\x01\x01\x12G\n\nface_point\x18\x06 \x01(\x0b\x32..com.tencent.qqlive.protocol.pb.ImageFacePointH\x05\x88\x01\x01\x42\x08\n\x06_titleB\x0c\n\n_sub_titleB\x0e\n\x0c_third_titleB\x0c\n\n_image_urlB\x10\n\x0e_picture_ratioB\r\n\x0b_face_pointb\x06proto3'
  ,
  dependencies=[pyproto_dot_com_dot_tencent_dot_qqlive_dot_protocol_dot_pb_dot_ImageFacePoint__pb2.DESCRIPTOR,])




_POSTER = _descriptor.Descriptor(
  name='Poster',
  full_name='com.tencent.qqlive.protocol.pb.Poster',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='com.tencent.qqlive.protocol.pb.Poster.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sub_title', full_name='com.tencent.qqlive.protocol.pb.Poster.sub_title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='third_title', full_name='com.tencent.qqlive.protocol.pb.Poster.third_title', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='image_url', full_name='com.tencent.qqlive.protocol.pb.Poster.image_url', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='picture_ratio', full_name='com.tencent.qqlive.protocol.pb.Poster.picture_ratio', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='face_point', full_name='com.tencent.qqlive.protocol.pb.Poster.face_point', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_title', full_name='com.tencent.qqlive.protocol.pb.Poster._title',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_sub_title', full_name='com.tencent.qqlive.protocol.pb.Poster._sub_title',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_third_title', full_name='com.tencent.qqlive.protocol.pb.Poster._third_title',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_image_url', full_name='com.tencent.qqlive.protocol.pb.Poster._image_url',
      index=3, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_picture_ratio', full_name='com.tencent.qqlive.protocol.pb.Poster._picture_ratio',
      index=4, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_face_point', full_name='com.tencent.qqlive.protocol.pb.Poster._face_point',
      index=5, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=149,
  serialized_end=439,
)

_POSTER.fields_by_name['face_point'].message_type = pyproto_dot_com_dot_tencent_dot_qqlive_dot_protocol_dot_pb_dot_ImageFacePoint__pb2._IMAGEFACEPOINT
_POSTER.oneofs_by_name['_title'].fields.append(
  _POSTER.fields_by_name['title'])
_POSTER.fields_by_name['title'].containing_oneof = _POSTER.oneofs_by_name['_title']
_POSTER.oneofs_by_name['_sub_title'].fields.append(
  _POSTER.fields_by_name['sub_title'])
_POSTER.fields_by_name['sub_title'].containing_oneof = _POSTER.oneofs_by_name['_sub_title']
_POSTER.oneofs_by_name['_third_title'].fields.append(
  _POSTER.fields_by_name['third_title'])
_POSTER.fields_by_name['third_title'].containing_oneof = _POSTER.oneofs_by_name['_third_title']
_POSTER.oneofs_by_name['_image_url'].fields.append(
  _POSTER.fields_by_name['image_url'])
_POSTER.fields_by_name['image_url'].containing_oneof = _POSTER.oneofs_by_name['_image_url']
_POSTER.oneofs_by_name['_picture_ratio'].fields.append(
  _POSTER.fields_by_name['picture_ratio'])
_POSTER.fields_by_name['picture_ratio'].containing_oneof = _POSTER.oneofs_by_name['_picture_ratio']
_POSTER.oneofs_by_name['_face_point'].fields.append(
  _POSTER.fields_by_name['face_point'])
_POSTER.fields_by_name['face_point'].containing_oneof = _POSTER.oneofs_by_name['_face_point']
DESCRIPTOR.message_types_by_name['Poster'] = _POSTER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Poster = _reflection.GeneratedProtocolMessageType('Poster', (_message.Message,), {
  'DESCRIPTOR' : _POSTER,
  '__module__' : 'pyproto.com.tencent.qqlive.protocol.pb.Poster_pb2'
  # @@protoc_insertion_point(class_scope:com.tencent.qqlive.protocol.pb.Poster)
  })
_sym_db.RegisterMessage(Poster)


# @@protoc_insertion_point(module_scope)
