# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pyproto/com.tencent.qqlive.protocol.pb.SectionType.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pyproto/com.tencent.qqlive.protocol.pb.SectionType.proto',
  package='com.tencent.qqlive.protocol.pb',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n8pyproto/com.tencent.qqlive.protocol.pb.SectionType.proto\x12\x1e\x63om.tencent.qqlive.protocol.pb*\xb3\x01\n\x0bSectionType\x12\x1d\n\x19SECTION_TYPE_SINGLE_BLOCK\x10\x00\x12%\n\x18SECTION_TYPE_UNSPECIFIED\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\x1b\n\x17SECTION_TYPE_BLOCK_LIST\x10\x01\x12\"\n\x1eSECTION_TYPE_COLLECTION_BLOCKS\x10\x02\x12\x1d\n\x17SECTION_TYPE_JCE_CUSTOM\x10\xa1\x8d\x06\x62\x06proto3'
)

_SECTIONTYPE = _descriptor.EnumDescriptor(
  name='SectionType',
  full_name='com.tencent.qqlive.protocol.pb.SectionType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SECTION_TYPE_SINGLE_BLOCK', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SECTION_TYPE_UNSPECIFIED', index=1, number=-1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SECTION_TYPE_BLOCK_LIST', index=2, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SECTION_TYPE_COLLECTION_BLOCKS', index=3, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SECTION_TYPE_JCE_CUSTOM', index=4, number=100001,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=93,
  serialized_end=272,
)
_sym_db.RegisterEnumDescriptor(_SECTIONTYPE)

SectionType = enum_type_wrapper.EnumTypeWrapper(_SECTIONTYPE)
SECTION_TYPE_SINGLE_BLOCK = 0
SECTION_TYPE_UNSPECIFIED = -1
SECTION_TYPE_BLOCK_LIST = 1
SECTION_TYPE_COLLECTION_BLOCKS = 2
SECTION_TYPE_JCE_CUSTOM = 100001


DESCRIPTOR.enum_types_by_name['SectionType'] = _SECTIONTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
