# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pyproto/com.tencent.qqlive.protocol.pb.VideoIdKeyValueSetKey.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pyproto/com.tencent.qqlive.protocol.pb.VideoIdKeyValueSetKey.proto',
  package='com.tencent.qqlive.protocol.pb',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nBpyproto/com.tencent.qqlive.protocol.pb.VideoIdKeyValueSetKey.proto\x12\x1e\x63om.tencent.qqlive.protocol.pb*\x94\x02\n\x15VideoIdKeyValueSetKey\x12&\n\"VIDEO_ID_KEY_VALUE_SET_KEY_DEFAULT\x10\x00\x12\'\n#VIDEO_ID_KEY_VALUE_SET_KEY_VIDEO_ID\x10\x01\x12\'\n#VIDEO_ID_KEY_VALUE_SET_KEY_COVER_ID\x10\x02\x12(\n$VIDEO_ID_KEY_VALUE_SET_KEY_COLUMN_ID\x10\x03\x12)\n%VIDEO_ID_KEY_VALUE_SET_KEY_PROGRAM_ID\x10\x04\x12,\n(VIDEO_ID_KEY_VALUE_SET_KEY_VIDEO_SHORTID\x10\x05\x62\x06proto3'
)

_VIDEOIDKEYVALUESETKEY = _descriptor.EnumDescriptor(
  name='VideoIdKeyValueSetKey',
  full_name='com.tencent.qqlive.protocol.pb.VideoIdKeyValueSetKey',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='VIDEO_ID_KEY_VALUE_SET_KEY_DEFAULT', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='VIDEO_ID_KEY_VALUE_SET_KEY_VIDEO_ID', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='VIDEO_ID_KEY_VALUE_SET_KEY_COVER_ID', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='VIDEO_ID_KEY_VALUE_SET_KEY_COLUMN_ID', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='VIDEO_ID_KEY_VALUE_SET_KEY_PROGRAM_ID', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='VIDEO_ID_KEY_VALUE_SET_KEY_VIDEO_SHORTID', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=103,
  serialized_end=379,
)
_sym_db.RegisterEnumDescriptor(_VIDEOIDKEYVALUESETKEY)

VideoIdKeyValueSetKey = enum_type_wrapper.EnumTypeWrapper(_VIDEOIDKEYVALUESETKEY)
VIDEO_ID_KEY_VALUE_SET_KEY_DEFAULT = 0
VIDEO_ID_KEY_VALUE_SET_KEY_VIDEO_ID = 1
VIDEO_ID_KEY_VALUE_SET_KEY_COVER_ID = 2
VIDEO_ID_KEY_VALUE_SET_KEY_COLUMN_ID = 3
VIDEO_ID_KEY_VALUE_SET_KEY_PROGRAM_ID = 4
VIDEO_ID_KEY_VALUE_SET_KEY_VIDEO_SHORTID = 5


DESCRIPTOR.enum_types_by_name['VideoIdKeyValueSetKey'] = _VIDEOIDKEYVALUESETKEY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
